/**
 * GENERATED by scripts/emit-attribution.mjs — do not edit by hand.
 *
 * The third-party attribution list rendered at /attribution (#215). Regenerate with
 * `pnpm emit:attribution`; `pnpm check:attribution` (and attribution.generated.test.ts) fail
 * if this file is stale relative to the installed dependencies and the font licence record.
 */

export interface RuntimeDependency {
  readonly name: string;
  readonly version: string;
  readonly licence: string;
  readonly homepage: string;
}

export interface FontAttribution {
  readonly family: string;
  readonly licence: string;
  readonly licenceUrl: string;
  readonly author: string;
  readonly source: string;
}

export const RUNTIME_DEPENDENCIES: readonly RuntimeDependency[] = [
  {
    "name": "next",
    "version": "15.5.25",
    "licence": "MIT",
    "homepage": "https://nextjs.org"
  },
  {
    "name": "react",
    "version": "19.2.8",
    "licence": "MIT",
    "homepage": "https://react.dev/"
  },
  {
    "name": "react-dom",
    "version": "19.2.8",
    "licence": "MIT",
    "homepage": "https://react.dev/"
  },
  {
    "name": "zod",
    "version": "3.25.76",
    "licence": "MIT",
    "homepage": "https://zod.dev"
  }
];

export const FONT_ATTRIBUTIONS: readonly FontAttribution[] = [
  {
    "family": "Fredoka",
    "licence": "OFL-1.1",
    "licenceUrl": "https://openfontlicense.org/open-font-license-official-text/",
    "author": "Milena Brandão and Hafontia — The Fredoka Project Authors (Copyright 2016)",
    "source": "https://fonts.google.com/specimen/Fredoka — https://github.com/google/fonts/tree/main/ofl/fredoka"
  },
  {
    "family": "JetBrains Mono",
    "licence": "OFL-1.1",
    "licenceUrl": "https://openfontlicense.org/open-font-license-official-text/",
    "author": "Philipp Nurullin and Konstantin Bulenkov, JetBrains — The JetBrains Mono Project Authors (Copyright 2020)",
    "source": "https://fonts.google.com/specimen/JetBrains+Mono — https://github.com/JetBrains/JetBrainsMono"
  },
  {
    "family": "Noto Sans Arabic",
    "licence": "OFL-1.1",
    "licenceUrl": "https://openfontlicense.org/open-font-license-official-text/",
    "author": "The Noto Project Authors (Copyright 2022, https://github.com/notofonts/arabic)",
    "source": "https://fonts.google.com/noto/specimen/Noto+Sans+Arabic — https://github.com/notofonts/arabic — fetched 2026-09-12 from https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@400..700&display=swap (the 'arabic' block; request, User-Agent and sha256 in src/styles/fonts.css)"
  },
  {
    "family": "Noto Sans Devanagari",
    "licence": "OFL-1.1",
    "licenceUrl": "https://openfontlicense.org/open-font-license-official-text/",
    "author": "The Noto Project Authors (Copyright 2022, https://github.com/notofonts/devanagari)",
    "source": "https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari — https://github.com/notofonts/devanagari — fetched 2026-09-12 from https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@400..700&display=swap (the 'devanagari' block; request, User-Agent and sha256 in src/styles/fonts.css)"
  },
  {
    "family": "Plus Jakarta Sans",
    "licence": "OFL-1.1",
    "licenceUrl": "https://openfontlicense.org/open-font-license-official-text/",
    "author": "Tokotype — The Plus Jakarta Sans Project Authors (Copyright 2020)",
    "source": "https://fonts.google.com/specimen/Plus+Jakarta+Sans — https://github.com/tokotype/PlusJakartaSans"
  }
];
