import { Rng, otherSeat } from '@duelbox/engine';
import type { SeatId } from '@duelbox/engine';
import { DEFAULT_SEARCH_NODES, SearchBudget, deepen, resolve } from '@duelbox/game-sdk';
import type { WinCondition } from '@duelbox/game-sdk';

/**
 * The rules of a two-seat sliding puzzle, with nothing else in them.
 *
 * No rendering, no timing, no DOM: the game, the bot and the balance harness all read the
 * board through these functions, so there is exactly one definition of what a legal slide
 * is and of who has won.
 *
 * ## What makes a sliding puzzle a duel
 *
 * One board, one gap, alternating slides — and **two goals that are the same goal seen
 * from two chairs**. Seat one wants the tiles in reading order from where seat one sits;
 * seat two wants them in reading order from where seat two sits. Those two arrangements
 * are each other's half-turn, which is exactly the half-turn the shell already makes when
 * the board changes hands. So the seat rotation stops being decoration and becomes the
 * rule: every slide that carries a tile towards one player's order carries it away from
 * the other's, and neither player is solving a different puzzle from the one in front of
 * them.
 *
 * Two facts make that fair rather than merely symmetric, and both are proved in the tests:
 *
 * 1. **Both goals live in the same orbit.** Half of all permutations of a sliding puzzle
 *    cannot be reached from the solved board at all, so "the other player's goal" could
 *    easily have been unreachable. On a 3x3 it is reachable — the half-turn is an even
 *    permutation and moves the gap an even taxicab distance — and the board is only ever
 *    generated by *playing legal moves*, so every position we ship is solvable to both
 *    goals by construction.
 * 2. **The rules are invariant under the half-turn.** Rotating a position 180 degrees
 *    swaps the two seats' scores exactly and maps legal moves onto legal moves, so a
 *    match and its mirror are the same match with the chairs swapped. The shuffle flips a
 *    seeded coin and rotates, which makes the *distribution* of starting positions
 *    invariant too — there is no residual seat bias left for tuning to hide.
 */

/** Cells on a side. Three, and the reasoning for that is in SPEC.md. */
export const SIZE = 3;
export const CELL_COUNT = SIZE * SIZE;
/** Numbered tiles. The odd one out is the gap. */
export const TILE_COUNT = CELL_COUNT - 1;
/** The empty square, as a board value. Tiles are 1..TILE_COUNT. */
export const GAP = 0;

/**
 * How many slides each seat gets. The match ends when both budgets are spent, and nothing
 * that happens on the board can add one — which is the whole of this game's termination
 * argument. `roundSeconds` ends nothing anywhere in this repository.
 */
export const MOVES_PER_SEAT = 23;

/**
 * Slides in a turn — and the single most important number in this game.
 *
 * **One slide a turn is unplayable, and the measurement is not close.** Under strict
 * alternation the seat that *replies* won 99.7% at `hard`, 95.9% at `normal` and 77.8% at
 * `easy` over 600 matches a tier. Two uniformly random seats split 50/50 on the same
 * boards, so it is neither the shuffle nor the seats: the better both sides play, the worse
 * it is to be the one who has to commit first. Every slide gains something, and the replier
 * takes the larger half of every exchange, twenty-three exchanges running.
 *
 * Ending the match on the opener's slide instead of the replier's changed it by 0.1 of a
 * point, so it was never about the last word. It was about who answers whom.
 *
 * Turns of two slides, with the opening turn and the closing turn cut to one, hand the
 * reply back and forth: the order runs A, BB, AA, BB, ..., AA, B — the same order read
 * backwards with the chairs swapped, which is asserted in the tests. Each seat still makes
 * {@link MOVES_PER_SEAT} slides, and the opening seat's share falls from 99.7% to 48-52%.
 *
 * A Thue-Morse order — the textbook answer to exactly this problem — was tried too and came
 * out slightly worse (55-56%) as well as being impossible to explain to a player.
 */
export const SLIDES_PER_TURN = 2;

/** Directions the *gap* travels. A key or a tap names the tile on that side of it. */
export const UP = 0;
export const RIGHT = 1;
export const DOWN = 2;
export const LEFT = 3;
export const DIRECTION_COUNT = 4;

/** Up and down, left and right: two bits, so the reverse of a direction is one xor. */
export function opposite(direction: number): number {
  return direction ^ 2;
}

/** Cell the gap reaches by moving one step, or -1 when that runs off the board. */
export function stepCell(cell: number, direction: number): number {
  if (cell < 0 || cell >= CELL_COUNT) return -1;
  const row = Math.floor(cell / SIZE);
  const column = cell % SIZE;
  switch (direction) {
    case UP:
      return row === 0 ? -1 : cell - SIZE;
    case RIGHT:
      return column === SIZE - 1 ? -1 : cell + 1;
    case DOWN:
      return row === SIZE - 1 ? -1 : cell + SIZE;
    case LEFT:
      return column === 0 ? -1 : cell - 1;
    default:
      return -1;
  }
}

/** The half-turn on cells. Its own inverse, which is why one function serves both seats. */
export function rotateCell(cell: number): number {
  return CELL_COUNT - 1 - cell;
}

/**
 * Where a tile belongs, for one seat.
 *
 * Seat one reads the board from the top left, so tile `v` belongs in cell `v - 1`. Seat
 * two reads the same board from the other side, so their home cell is the half-turn of
 * seat one's: `rotateCell(v - 1)`, which is `CELL_COUNT - v`.
 *
 * On an odd board the centre is its own half-turn, so tile 5 has the same home for both
 * players. That single shared cell is the only cooperative square on the board.
 */
export function homeCellFor(seat: SeatId, value: number): number {
  return seat === 'p1' ? value - 1 : CELL_COUNT - value;
}

/** Taxicab distance between two cells, in cells. */
export function cellDistance(a: number, b: number): number {
  const rows = Math.floor(a / SIZE) - Math.floor(b / SIZE);
  const columns = (a % SIZE) - (b % SIZE);
  return Math.abs(rows) + Math.abs(columns);
}

/**
 * The live board and the state that decides a match.
 *
 * Flat and mutable on purpose: a match is stepped inside a fixed timestep that may not
 * allocate, and the balance harness plays thousands of them.
 */
export interface Match {
  /** Cell `c` holds a tile value in 1..TILE_COUNT, or {@link GAP}. */
  readonly board: number[];
  /** Cell the gap is in. Derived from `board`, kept alongside so a move is O(1). */
  gap: number;
  /** Direction the gap moved on the last slide, or -1 before the first one. */
  lastDirection: number;
  active: SeatId;
  /** Slides left in the active seat's turn. One on the opening turn, two after it. */
  turnSlides: number;
  /** Slides each seat has left. */
  p1Moves: number;
  p2Moves: number;
  /**
   * The most tiles this seat has ever had standing in its own order at once, and the
   * closest its whole board has ever come to that order. Both are best-ever marks that
   * only ever improve — see {@link bank} for why the score cannot be a reading of the
   * final position.
   */
  p1Best: number;
  p2Best: number;
  p1Closest: number;
  p2Closest: number;
  winner: SeatId | 'draw' | null;
  /** The tile the last slide moved, and where it came from and went. For the renderer. */
  movedValue: number;
  movedFrom: number;
  movedTo: number;
}

export function createMatch(): Match {
  const board: number[] = [];
  for (let i = 0; i < CELL_COUNT; i += 1) board.push(GAP);
  return {
    board,
    gap: CELL_COUNT - 1,
    lastDirection: -1,
    active: 'p1',
    turnSlides: 1,
    p1Moves: MOVES_PER_SEAT,
    p2Moves: MOVES_PER_SEAT,
    p1Best: 0,
    p2Best: 0,
    p1Closest: 0,
    p2Closest: 0,
    winner: null,
    movedValue: GAP,
    movedFrom: -1,
    movedTo: -1,
  };
}

/** Reads through `noUncheckedIndexedAccess`; an out-of-range cell reads as the gap. */
function valueAt(board: readonly number[], cell: number): number {
  return board[cell] ?? GAP;
}

/** Seat one's finished board: 1..8 in reading order with the gap in the last cell. */
export function solvedInto(board: number[]): void {
  for (let cell = 0; cell < CELL_COUNT - 1; cell += 1) board[cell] = cell + 1;
  board[CELL_COUNT - 1] = GAP;
}

/** Turn a board half way round in place. The involution the whole game is built on. */
export function rotateBoard(board: number[]): void {
  for (let cell = 0; cell < Math.floor(CELL_COUNT / 2); cell += 1) {
    const far = rotateCell(cell);
    const held = valueAt(board, cell);
    board[cell] = valueAt(board, far);
    board[far] = held;
  }
}

/** Tiles standing in their home cell for `seat`, right now. */
export function homeCount(board: readonly number[], seat: SeatId): number {
  let count = 0;
  for (let cell = 0; cell < CELL_COUNT; cell += 1) {
    const value = valueAt(board, cell);
    if (value === GAP) continue;
    if (homeCellFor(seat, value) === cell) count += 1;
  }
  return count;
}

/**
 * How far every tile is from where `seat` wants it, summed. The tiebreak, and the only
 * measure that moves on every single slide.
 */
export function homeDistance(board: readonly number[], seat: SeatId): number {
  let total = 0;
  for (let cell = 0; cell < CELL_COUNT; cell += 1) {
    const value = valueAt(board, cell);
    if (value === GAP) continue;
    total += cellDistance(cell, homeCellFor(seat, value));
  }
  return total;
}

/**
 * The legal slides in a position, written into `out` from `offset`, and how many there are.
 *
 * Two rules, and the second is the one that makes the game a game. A slide is legal when
 * the gap can travel that way, and when it is **not the exact reverse of the slide just
 * played**: without that, every move a player makes is undone by the reply, and two seats
 * pushing towards opposite goals simply oscillate for the whole match.
 *
 * The gap always has at least two neighbours on a board this size, so banning one reverse
 * can never leave a player with nothing to do. There is no pass rule because there cannot
 * be a position that needs one.
 */
export function legalMovesInto(
  gap: number,
  lastDirection: number,
  out: number[],
  offset = 0,
): number {
  const banned = lastDirection < 0 ? -1 : opposite(lastDirection);
  let count = 0;
  for (let direction = 0; direction < DIRECTION_COUNT; direction += 1) {
    if (direction === banned) continue;
    if (stepCell(gap, direction) < 0) continue;
    out[offset + count] = direction;
    count += 1;
  }
  return count;
}

/** Whether `direction` is a slide this position allows. */
export function isLegalMove(match: Readonly<Match>, direction: number): boolean {
  if (direction < 0 || direction >= DIRECTION_COUNT) return false;
  if (match.winner !== null) return false;
  if (match.lastDirection >= 0 && direction === opposite(match.lastDirection)) return false;
  return stepCell(match.gap, direction) >= 0;
}

/** How many slides `seat` has left. */
export function movesLeft(match: Readonly<Match>, seat: SeatId): number {
  return seat === 'p1' ? match.p1Moves : match.p2Moves;
}

/** Slides the seat taking over would get. The tail of a budget shortens the last turn. */
function turnLengthFor(remaining: number): number {
  return remaining < SLIDES_PER_TURN ? remaining : SLIDES_PER_TURN;
}

/**
 * Take the best-ever marks up to what the board shows now.
 *
 * **The score is a high-water mark rather than a reading of the final board.** Scoring the
 * final position is the obvious rule and it is the wrong one here: a player who spends
 * twenty slides building an arrangement can have it taken apart by the opponent's last
 * slide, so what the match measures is who moved most recently rather than who played best.
 *
 * On its own this did not fix the reply advantage — see {@link SLIDES_PER_TURN}, which is
 * what did — and it is worth being exact about that rather than claiming both. Under strict
 * alternation, final-position scoring gave the replying seat 99.9% at `hard`, 90.1% at
 * `normal` and 73.2% at `easy`; banking the best moved those to 99.7%, 95.9% and 77.8%,
 * which is to say it moved nothing. It earns its place for the other reason.
 *
 * It is the more honest rule for this puzzle. "The neatest arrangement you managed" is what
 * a person playing a sliding puzzle is proud of, and being one tile from a finished board
 * when the slides run out is not less of an achievement because the other player nudged a
 * tile afterwards. It also gives the shell a score that only ever climbs.
 */
export function bank(match: Match): void {
  const p1Home = homeCount(match.board, 'p1');
  const p2Home = homeCount(match.board, 'p2');
  if (p1Home > match.p1Best) match.p1Best = p1Home;
  if (p2Home > match.p2Best) match.p2Best = p2Home;
  const p1Distance = homeDistance(match.board, 'p1');
  const p2Distance = homeDistance(match.board, 'p2');
  if (p1Distance < match.p1Closest) match.p1Closest = p1Distance;
  if (p2Distance < match.p2Closest) match.p2Closest = p2Distance;
}

const CONDITION: WinCondition = { kind: 'highest-when-time-expires' };
/** Reused so judging a position allocates nothing; a match is judged after every slide. */
const tally = { p1: 0, p2: 0 };
const timeExpired = { timeExpired: true };

/**
 * Decide the match, or null while it is still running.
 *
 * Filling the board in your own order wins on the spot — that is what a sliding puzzle
 * means, and the two orders are exclusive everywhere but the centre, so both seats can
 * never claim it at once. Otherwise the seat whose best arrangement held more tiles takes
 * it, and a tie there goes to whoever came closest to their own order.
 *
 * The closest-approach tiebreak is not decoration. A best arrangement is an integer
 * between nought and eight and two players of the same standard land on the same one of
 * those nine values often; the measured draw rates with and without it are in SPEC.md.
 */
export function judge(match: Readonly<Match>): SeatId | 'draw' | null {
  if (homeCount(match.board, 'p1') === TILE_COUNT) return 'p1';
  if (homeCount(match.board, 'p2') === TILE_COUNT) return 'p2';
  if (match.p1Moves > 0 || match.p2Moves > 0) return null;

  tally.p1 = match.p1Best;
  tally.p2 = match.p2Best;
  const outcome = resolve(CONDITION, tally, timeExpired);
  if (outcome !== 'draw') return outcome;
  if (match.p1Closest === match.p2Closest) return 'draw';
  return match.p1Closest < match.p2Closest ? 'p1' : 'p2';
}

export function winnerOf(match: Readonly<Match>): SeatId | 'draw' | null {
  return match.winner;
}

/**
 * Play a slide. Returns false and changes nothing when it is not one this position allows,
 * so a caller may offer any tap or key at all.
 */
export function applyMove(match: Match, direction: number): boolean {
  if (!isLegalMove(match, direction)) return false;
  const from = stepCell(match.gap, direction);
  if (from < 0) return false;

  const value = valueAt(match.board, from);
  match.board[match.gap] = value;
  match.board[from] = GAP;
  match.movedValue = value;
  match.movedFrom = from;
  match.movedTo = match.gap;
  match.gap = from;
  match.lastDirection = direction;

  if (match.active === 'p1') match.p1Moves -= 1;
  else match.p2Moves -= 1;
  match.turnSlides -= 1;

  // Both seats' marks are taken from every position, whoever produced it: the board is
  // shared, so an arrangement is an arrangement however it came about.
  bank(match);
  match.winner = judge(match);
  if (match.winner !== null) return true;

  if (match.turnSlides <= 0 || movesLeft(match, match.active) === 0) {
    const next = otherSeat(match.active);
    match.active = next;
    match.turnSlides = turnLengthFor(movesLeft(match, next));
  }
  return true;
}

/* -------------------------------------------------------------------------- */
/* The shuffle, and why it is not a shuffle                                     */
/* -------------------------------------------------------------------------- */

/**
 * How many legal slides the generator plays away from the finished board.
 *
 * Long enough that the walk reaches the middle ground between the two goals — the two
 * finished boards are twenty taxicab units apart, so a position equidistant from both is
 * at least ten from each — and short enough that the acceptance test below is met inside
 * a handful of attempts. Measured; the numbers are in SPEC.md.
 */
export const SHUFFLE_WALK = 22;

/**
 * How many walks to try before settling for the best one seen.
 *
 * Bounded because this runs in `init` on whatever seed the shell hands over, and an
 * unbounded search for a perfectly balanced start is a hang waiting for an unlucky seed.
 * About one walk in twenty is accepted, so 200 leaves a three-in-a-hundred-thousand chance
 * of falling back to the best walk seen; over 20000 seeds the fallback has never been
 * taken, and the tests assert it. Two hundred walks of twenty-two slides is 4400 array
 * writes, once, in `init`.
 */
export const SHUFFLE_ATTEMPTS = 200;

const walkBoard: number[] = new Array<number>(CELL_COUNT).fill(GAP);
const bestBoard: number[] = new Array<number>(CELL_COUNT).fill(GAP);
const walkMoves: number[] = new Array<number>(DIRECTION_COUNT).fill(0);

/**
 * How unbalanced a candidate start is. Zero is a start the two seats are equally placed
 * in: the same number of tiles home and the same total distance to go.
 *
 * Distance is weighted above tiles home because it is the finer measure — two positions
 * can agree on tiles home and be four moves apart in real progress.
 */
function imbalanceOf(board: readonly number[]): number {
  const p1Home = homeCount(board, 'p1');
  const p2Home = homeCount(board, 'p2');
  const p1Distance = homeDistance(board, 'p1');
  const p2Distance = homeDistance(board, 'p2');
  return Math.abs(p1Distance - p2Distance) * 4 + Math.abs(p1Home - p2Home);
}

/**
 * A start position, generated by **playing legal slides from the finished board** rather
 * than by permuting tiles.
 *
 * This is not a stylistic choice. Exactly half of the 9! arrangements of a 3x3 sliding
 * puzzle cannot be reached from the finished board by any sequence of slides, so a
 * shuffle that permutes tiles ships a puzzle that is impossible one time in two. A walk
 * of legal moves can only ever land inside the reachable half, and the test proves it by
 * enumerating that half — all 181440 of it — and checking every generated board is a
 * member.
 *
 * The walk never immediately retraces its own step, for the same reason the game bans a
 * takeback: a walk that may undo itself spends much of its length standing still.
 *
 * Two more things happen here, both about fairness rather than solvability:
 *
 * - **Attempts are rejected until the two seats start level**, on tiles home and on
 *   distance to go alike. The walk starts at *seat one's* finished board, so an
 *   unfiltered walk hands seat one a head start that no bot tuning could undo.
 * - **A seeded coin decides whether to turn the result half way round.** Rotating maps
 *   the accepted set onto itself and swaps the two seats' positions exactly, so the
 *   distribution this returns is invariant under the half-turn — the two seats are not
 *   merely level on two summary numbers, they face the same distribution of boards.
 */
export function shuffleInto(board: number[], rng: Rng): void {
  let bestImbalance = Number.POSITIVE_INFINITY;

  for (let attempt = 0; attempt < SHUFFLE_ATTEMPTS; attempt += 1) {
    solvedInto(walkBoard);
    let gap = CELL_COUNT - 1;
    let last = -1;
    for (let step = 0; step < SHUFFLE_WALK; step += 1) {
      const count = legalMovesInto(gap, last, walkMoves);
      const direction = walkMoves[rng.int(0, count)] ?? UP;
      const from = stepCell(gap, direction);
      if (from < 0) continue;
      walkBoard[gap] = valueAt(walkBoard, from);
      walkBoard[from] = GAP;
      gap = from;
      last = direction;
    }

    const imbalance = imbalanceOf(walkBoard);
    if (imbalance < bestImbalance) {
      bestImbalance = imbalance;
      for (let cell = 0; cell < CELL_COUNT; cell += 1) bestBoard[cell] = valueAt(walkBoard, cell);
    }
    if (bestImbalance === 0) break;
  }

  for (let cell = 0; cell < CELL_COUNT; cell += 1) board[cell] = valueAt(bestBoard, cell);
  if (rng.bool()) rotateBoard(board);
}

/** Where the gap ended up. */
export function gapOf(board: readonly number[]): number {
  for (let cell = 0; cell < CELL_COUNT; cell += 1) {
    if (valueAt(board, cell) === GAP) return cell;
  }
  return CELL_COUNT - 1;
}

/**
 * Deal a fresh match.
 *
 * `openingSeat` comes from the shell, which alternates it across the rounds of a best-of
 * so that first-mover advantage washes out. A game that assumed `p1` would hand the
 * opener's edge to the same person every round.
 */
export function resetMatch(match: Match, rng: Rng, openingSeat: SeatId): void {
  shuffleInto(match.board, rng);
  match.gap = gapOf(match.board);
  match.lastDirection = -1;
  match.active = openingSeat;
  // The opening turn is a single slide, and the closing turn falls out to a single one
  // too: that is what makes the two seats reply to each other the same number of times.
  match.turnSlides = 1;
  match.p1Moves = MOVES_PER_SEAT;
  match.p2Moves = MOVES_PER_SEAT;
  match.p1Best = homeCount(match.board, 'p1');
  match.p2Best = homeCount(match.board, 'p2');
  match.p1Closest = homeDistance(match.board, 'p1');
  match.p2Closest = homeDistance(match.board, 'p2');
  match.winner = null;
  match.movedValue = GAP;
  match.movedFrom = -1;
  match.movedTo = -1;
}

/* -------------------------------------------------------------------------- */
/* The bot                                                                      */
/* -------------------------------------------------------------------------- */

export type BotDifficulty = 'easy' | 'normal' | 'hard';

/**
 * How many slides each tier looks ahead.
 *
 * Difficulty is only ever how far the bot sees and how often it throws the position away.
 * No tier reads anything a player sitting at the board cannot read, none gets an extra
 * slide, and none of them knows the solution — the evaluation below is the win condition
 * written out, and a player can count tiles home just as well.
 *
 * **Every depth is even, and that is load-bearing.** A turn is two slides, so an odd depth
 * stops half way through somebody's turn and values a position in which one seat still has
 * a slide in hand. Depth three gave `normal` a 56.4% opening-seat win rate; depth four,
 * one ply deeper and ending on the turn boundary, brought it to 51.3% with everything else
 * untouched. The horizon has to line up with the turn or the search is answering a
 * different question from the one the match asks.
 */
export const SEARCH_DEPTH: Readonly<Record<BotDifficulty, number>> = Object.freeze({
  easy: 2,
  normal: 4,
  hard: 6,
});

/** How often a tier abandons its search and slides a uniformly random legal tile. */
export const BLUNDER_CHANCE: Readonly<Record<BotDifficulty, number>> = Object.freeze({
  easy: 0.45,
  normal: 0.15,
  hard: 0,
});

/**
 * Values a bot draws from its generator per move, whatever it decides to do.
 *
 * Constant on purpose. Both draws happen before anything branches, so the generator
 * advances by the same amount whether the bot blunders or searches — a conditional draw
 * couples one seat's stream to how its opponent happens to be playing.
 */
export const BOT_DRAWS_PER_MOVE = 2;

/**
 * Filling the board wins outright, so it must outrank every position that has not.
 * Reduced by the ply so a solve two moves away is preferred to the same solve four away.
 */
const WIN_SCORE = 1_000_000;
const SCORE_FLOOR = -(WIN_SCORE + 1);

/**
 * The evaluation, written as weights, is **the win condition and nothing else**.
 *
 * Best arrangement first, closest approach as the tiebreak, exactly as {@link judge}
 * compares them — the weights are only chosen so that no amount of the lower term can
 * ever outweigh one unit of the higher one. Eight tiles are at most 32 units from home,
 * so a closest-approach term of +/-32 x 128 = +/-4096 cannot reach one banked tile at
 * 8192, and the live-position term of at most +/-64 cannot reach one unit of closest
 * approach at 128.
 *
 * The live term is not part of the win condition and is deliberately the smallest: a
 * depth-limited search that could not see past its horizon to a banked improvement would
 * otherwise find every move identical and pick the first. It orders positions the win
 * condition genuinely cannot tell apart, and never overrules it.
 */
export const BEST_WEIGHT = 8192;
export const CLOSEST_WEIGHT = 128;
export const LIVE_HOME_WEIGHT = 4;

/** The board the search mutates and undoes, so a search allocates nothing. */
const searchBoard: number[] = new Array<number>(CELL_COUNT).fill(GAP);
let searchGap = 0;
let searchLast = -1;
let searchP1Moves = 0;
let searchP2Moves = 0;
let searchTurnSlides = 1;
let searchSeat: SeatId = 'p1';
/** The banked marks carried down the tree, saved and restored around every slide. */
let searchP1Best = 0;
let searchP2Best = 0;
let searchP1Closest = 0;
let searchP2Closest = 0;

/** One slot per direction per ply, so generating moves at a node allocates nothing. */
const MAX_DEPTH = 10;
const moveStack: number[] = new Array<number>((MAX_DEPTH + 2) * DIRECTION_COUNT).fill(0);
/** Scratch for the blunder draw. */
const blunderMoves: number[] = new Array<number>(DIRECTION_COUNT).fill(0);

/** Filled by {@link measure}; read by the evaluation without walking the board twice. */
let measuredP1Home = 0;
let measuredP2Home = 0;
let measuredP1Distance = 0;
let measuredP2Distance = 0;

function measure(board: readonly number[]): void {
  let p1Home = 0;
  let p2Home = 0;
  let p1Distance = 0;
  let p2Distance = 0;
  for (let cell = 0; cell < CELL_COUNT; cell += 1) {
    const value = valueAt(board, cell);
    if (value === GAP) continue;
    const p1Cell = value - 1;
    const p2Cell = CELL_COUNT - value;
    if (p1Cell === cell) p1Home += 1;
    if (p2Cell === cell) p2Home += 1;
    p1Distance += cellDistance(cell, p1Cell);
    p2Distance += cellDistance(cell, p2Cell);
  }
  measuredP1Home = p1Home;
  measuredP2Home = p2Home;
  measuredP1Distance = p1Distance;
  measuredP2Distance = p2Distance;
}

/**
 * The banked marks, plus the last {@link measure}, read as a score for `seat`.
 *
 * Exactly antisymmetric — `staticScore('p1') === -staticScore('p2')` — which is what lets
 * the search be a plain negamax with no side-to-move corrections anywhere in it.
 */
function staticScore(seat: SeatId): number {
  const forP1 =
    BEST_WEIGHT * (searchP1Best - searchP2Best) +
    CLOSEST_WEIGHT * (searchP2Closest - searchP1Closest) +
    LIVE_HOME_WEIGHT * (measuredP1Home - measuredP2Home) +
    (measuredP2Distance - measuredP1Distance);
  return seat === 'p1' ? forP1 : -forP1;
}

/** Take the search's banked marks up to the position {@link measure} just read. */
function bankSearch(): void {
  if (measuredP1Home > searchP1Best) searchP1Best = measuredP1Home;
  if (measuredP2Home > searchP2Best) searchP2Best = measuredP2Home;
  if (measuredP1Distance < searchP1Closest) searchP1Closest = measuredP1Distance;
  if (measuredP2Distance < searchP2Closest) searchP2Closest = measuredP2Distance;
}

function searchMovesLeft(seat: SeatId): number {
  return seat === 'p1' ? searchP1Moves : searchP2Moves;
}

function spendSearchMove(seat: SeatId, delta: number): void {
  if (seat === 'p1') searchP1Moves += delta;
  else searchP2Moves += delta;
}

/**
 * Who slides next once `toMove` has just slid, updating the turn counter to match.
 *
 * The same seat continues while its turn has slides left, which is the whole reason this
 * exists: a search that assumed strict alternation would plan the first half of every
 * two-slide turn and hand the second one to the opponent in its head.
 */
function advanceSearchTurn(toMove: SeatId): SeatId {
  if (searchTurnSlides > 0 && searchMovesLeft(toMove) > 0) return toMove;
  const next = otherSeat(toMove);
  searchTurnSlides = turnLengthFor(searchMovesLeft(next));
  return next;
}

/** Slide on {@link searchBoard}. Returns the direction to restore on the way back up. */
function doSearchMove(direction: number): number {
  const from = stepCell(searchGap, direction);
  searchBoard[searchGap] = valueAt(searchBoard, from);
  searchBoard[from] = GAP;
  searchGap = from;
  const previous = searchLast;
  searchLast = direction;
  return previous;
}

function undoSearchMove(direction: number, previousLast: number): void {
  const back = stepCell(searchGap, opposite(direction));
  searchBoard[searchGap] = valueAt(searchBoard, back);
  searchBoard[back] = GAP;
  searchGap = back;
  searchLast = previousLast;
}

/**
 * Negamax with an alpha-beta window, scored from the point of view of `toMove`.
 *
 * The window only ever prunes branches whose value cannot change the choice made above
 * them, so the answer is the one an exhaustive search of the same depth gives.
 */
function search(
  toMove: SeatId,
  depth: number,
  ply: number,
  alpha: number,
  beta: number,
  budget: SearchBudget,
): number {
  // Charged on every node, leaves included: leaves are the overwhelming majority of the
  // work, and charging only internal nodes puts the ceiling above the thing it limits.
  const funded = budget.spend();
  measure(searchBoard);
  if (measuredP1Home === TILE_COUNT) {
    return toMove === 'p1' ? WIN_SCORE - ply : ply - WIN_SCORE;
  }
  if (measuredP2Home === TILE_COUNT) {
    return toMove === 'p2' ? WIN_SCORE - ply : ply - WIN_SCORE;
  }
  if (searchP1Moves === 0 && searchP2Moves === 0) return staticScore(toMove);
  if (!funded || depth <= 0) return staticScore(toMove);

  const base = ply * DIRECTION_COUNT;
  const count = legalMovesInto(searchGap, searchLast, moveStack, base);
  let best = SCORE_FLOOR;
  let lower = alpha;

  for (let i = 0; i < count; i += 1) {
    const direction = moveStack[base + i] ?? UP;
    const previousLast = doSearchMove(direction);
    const heldP1Best = searchP1Best;
    const heldP2Best = searchP2Best;
    const heldP1Closest = searchP1Closest;
    const heldP2Closest = searchP2Closest;
    const heldTurn = searchTurnSlides;
    measure(searchBoard);
    bankSearch();
    spendSearchMove(toMove, -1);
    searchTurnSlides -= 1;
    const next = advanceSearchTurn(toMove);
    // Negated only when the move passes to the other seat. A seat continuing its own turn
    // keeps the window and the sign, which is what makes a two-slide turn one plan.
    const score =
      next === toMove
        ? search(toMove, depth - 1, ply + 1, lower, beta, budget)
        : -search(next, depth - 1, ply + 1, -beta, -lower, budget);
    searchTurnSlides = heldTurn;
    spendSearchMove(toMove, 1);
    searchP1Best = heldP1Best;
    searchP2Best = heldP2Best;
    searchP1Closest = heldP1Closest;
    searchP2Closest = heldP2Closest;
    undoSearchMove(direction, previousLast);

    if (score > best) best = score;
    if (best > lower) lower = best;
    if (lower >= beta) break;
  }
  return best;
}

/**
 * The budget and the sweep are module-level so that a bot's move costs no allocation at
 * all, not even the closure `deepen` is handed.
 */
const searchBudget = new SearchBudget(DEFAULT_SEARCH_NODES);

/** One full sweep at a fixed depth, or null when the budget ran out part-way through. */
const sweep = (depth: number): number | null => {
  const count = legalMovesInto(searchGap, searchLast, moveStack, 0);
  const rootTurn = searchTurnSlides;
  let bestDirection = -1;
  let bestScore = SCORE_FLOOR;

  for (let i = 0; i < count; i += 1) {
    const direction = moveStack[i] ?? UP;
    const previousLast = doSearchMove(direction);
    const heldP1Best = searchP1Best;
    const heldP2Best = searchP2Best;
    const heldP1Closest = searchP1Closest;
    const heldP2Closest = searchP2Closest;
    measure(searchBoard);
    bankSearch();
    spendSearchMove(searchSeat, -1);
    searchTurnSlides -= 1;
    const next = advanceSearchTurn(searchSeat);
    const score =
      next === searchSeat
        ? search(searchSeat, depth - 1, 1, bestScore, Infinity, searchBudget)
        : -search(next, depth - 1, 1, -Infinity, -bestScore, searchBudget);
    searchTurnSlides = rootTurn;
    spendSearchMove(searchSeat, 1);
    searchP1Best = heldP1Best;
    searchP2Best = heldP2Best;
    searchP1Closest = heldP1Closest;
    searchP2Closest = heldP2Closest;
    undoSearchMove(direction, previousLast);

    if (searchBudget.exhausted) return null;
    if (bestDirection < 0 || score > bestScore) {
      bestScore = score;
      bestDirection = direction;
    }
  }
  return bestDirection;
};

/** Nodes the last {@link botMove} spent. For the cost tests and for SPEC.md. */
export function lastSearchNodes(): number {
  return searchBudget.spent;
}

/**
 * The slide `seat` should play, or -1 on a position with no legal slide — which this game
 * cannot produce, and which is answered rather than thrown so a caller never has to know.
 *
 * With the tier's blunder chance a uniformly random legal slide is played instead of the
 * searched one; otherwise the position is searched to the tier's depth under a
 * deterministic node budget, so the same board costs the same on a phone and on a laptop
 * and returns the same move. Ties break towards the lowest direction index, so the same
 * board and the same generator state always give the same slide.
 */
export function botMove(match: Readonly<Match>, rng: Rng, difficulty: BotDifficulty): number {
  const count = legalMovesInto(match.gap, match.lastDirection, blunderMoves);
  // Both draws happen here, unconditionally and before anything branches, so a seat's
  // stream advances by BOT_DRAWS_PER_MOVE however the move is decided.
  const blunder = rng.bool(BLUNDER_CHANCE[difficulty]);
  const ordinal = rng.int(0, count > 0 ? count : 1);
  searchBudget.reset();
  if (count === 0) return -1;
  if (blunder) return blunderMoves[ordinal] ?? -1;

  for (let cell = 0; cell < CELL_COUNT; cell += 1) searchBoard[cell] = valueAt(match.board, cell);
  searchGap = match.gap;
  searchLast = match.lastDirection;
  searchP1Moves = match.p1Moves;
  searchP2Moves = match.p2Moves;
  searchP1Best = match.p1Best;
  searchP2Best = match.p2Best;
  searchP1Closest = match.p1Closest;
  searchP2Closest = match.p2Closest;
  searchTurnSlides = match.turnSlides;
  searchSeat = match.active;

  const depth = Math.min(SEARCH_DEPTH[difficulty], MAX_DEPTH);
  const found = deepen(searchBudget, depth, sweep);
  return found >= 0 ? found : (blunderMoves[0] ?? -1);
}

/**
 * A generator per seat, derived once from the match seed.
 *
 * A shared stream is unbiased in a strict-alternation turn game *as long as* every turn
 * costs the same number of draws — and that is a property a later change breaks silently.
 * Two streams make the independence structural: seat two plays the identical slides
 * against `easy` and against `hard`, which is asserted in the tests.
 */
export function createBotRngs(rng: Rng): Readonly<Record<SeatId, Rng>> {
  return { p1: new Rng(rng.next() | 0), p2: new Rng(rng.next() | 0) };
}
