// Generated by `pnpm i18n:extract` (apps/web/src/lib/i18n/extract.test.ts) from every
// message the site can render. Do not edit by hand: change the source, or the transform in
// pseudo.ts, and regenerate. extract.test.ts fails when this file is not what it would write.

const catalogue = {
  locale: 'ar-XB',
  messages: {
    Language: '‮Language‬',
    'Mute sound': '‮Mute‬ ‮sound‬',
    'Only the language you choose is downloaded, and it applies straight away. Nothing is translated yet: the two pseudo languages are the English made deliberately strange, so that anything still in plain English is a string the translation work has not reached.':
      '‮Only‬ ‮the‬ ‮language‬ ‮you‬ ‮choose‬ ‮is‬ ‮downloaded,‬ ‮and‬ ‮it‬ ‮applies‬ ‮straight‬ ‮away.‬ ‮Nothing‬ ‮is‬ ‮translated‬ ‮yet:‬ ‮the‬ ‮two‬ ‮pseudo‬ ‮languages‬ ‮are‬ ‮the‬ ‮English‬ ‮made‬ ‮deliberately‬ ‮strange,‬ ‮so‬ ‮that‬ ‮anything‬ ‮still‬ ‮in‬ ‮plain‬ ‮English‬ ‮is‬ ‮a‬ ‮string‬ ‮the‬ ‮translation‬ ‮work‬ ‮has‬ ‮not‬ ‮reached.‬',
    Settings: '‮Settings‬',
    'Sound, vibration, and what this device remembers about how you play. Every change applies straight away and is kept in this browser only — nothing here is sent anywhere.':
      '‮Sound,‬ ‮vibration,‬ ‮and‬ ‮what‬ ‮this‬ ‮device‬ ‮remembers‬ ‮about‬ ‮how‬ ‮you‬ ‮play.‬ ‮Every‬ ‮change‬ ‮applies‬ ‮straight‬ ‮away‬ ‮and‬ ‮is‬ ‮kept‬ ‮in‬ ‮this‬ ‮browser‬ ‮only‬ ‮—‬ ‮nothing‬ ‮here‬ ‮is‬ ‮sent‬ ‮anywhere.‬',
    'Unmute sound': '‮Unmute‬ ‮sound‬',
  },
} as const;

export default catalogue;
