// Generated by `pnpm i18n:extract` (apps/web/src/lib/i18n/extract.test.ts) from every
// message the site can render. Do not edit by hand: change the source, or the transform in
// pseudo.ts, and regenerate. extract.test.ts fails when this file is not what it would write.

const catalogue = {
  locale: 'ar-XB',
  messages: {
    'A game asks the network for one thing, itself. Once its page and its code are on the device, the rules, the bot and the scoring all run here, which is why a match never waits for anything. So a game you have already played is still yours to play now.':
      '‮A‬ ‮game‬ ‮asks‬ ‮the‬ ‮network‬ ‮for‬ ‮one‬ ‮thing,‬ ‮itself.‬ ‮Once‬ ‮its‬ ‮page‬ ‮and‬ ‮its‬ ‮code‬ ‮are‬ ‮on‬ ‮the‬ ‮device,‬ ‮the‬ ‮rules,‬ ‮the‬ ‮bot‬ ‮and‬ ‮the‬ ‮scoring‬ ‮all‬ ‮run‬ ‮here,‬ ‮which‬ ‮is‬ ‮why‬ ‮a‬ ‮match‬ ‮never‬ ‮waits‬ ‮for‬ ‮anything.‬ ‮So‬ ‮a‬ ‮game‬ ‮you‬ ‮have‬ ‮already‬ ‮played‬ ‮is‬ ‮still‬ ‮yours‬ ‮to‬ ‮play‬ ‮now.‬',
    'A round takes about 1 minute.': '‮A‬ ‮round‬ ‮takes‬ ‮about‬ ‮1‬ ‮minute.‬',
    'A round takes about 2 minutes.': '‮A‬ ‮round‬ ‮takes‬ ‮about‬ ‮2‬ ‮minutes.‬',
    'A round takes about 40 seconds.': '‮A‬ ‮round‬ ‮takes‬ ‮about‬ ‮40‬ ‮seconds.‬',
    'A tournament is seven games drawn at random, one match each, beginning with the game you started it from. Whoever takes four has won it, and the line-up is written down on your device, so it survives closing the tab.':
      '‮A‬ ‮tournament‬ ‮is‬ ‮seven‬ ‮games‬ ‮drawn‬ ‮at‬ ‮random,‬ ‮one‬ ‮match‬ ‮each,‬ ‮beginning‬ ‮with‬ ‮the‬ ‮game‬ ‮you‬ ‮started‬ ‮it‬ ‮from.‬ ‮Whoever‬ ‮takes‬ ‮four‬ ‮has‬ ‮won‬ ‮it,‬ ‮and‬ ‮the‬ ‮line-up‬ ‮is‬ ‮written‬ ‮down‬ ‮on‬ ‮your‬ ‮device,‬ ‮so‬ ‮it‬ ‮survives‬ ‮closing‬ ‮the‬ ‮tab.‬',
    'Add {name} to favourites': '‮Add‬ {name} ‮to‬ ‮favourites‬',
    'All games': '‮All‬ ‮games‬',
    'All {count} games': '‮All‬ {count} ‮games‬',
    Arcade: '‮Arcade‬',
    'Arcade games': '‮Arcade‬ ‮games‬',
    Arena: '‮Arena‬',
    'Arena games': '‮Arena‬ ‮games‬',
    Attribution: '‮Attribution‬',
    Board: '‮Board‬',
    'Board games': '‮Board‬ ‮games‬',
    'Both players see the same thing at the same instant, and the only question is who answers first. Math Duel shows one sum and four answers, Match Rush hides a single shared symbol in two sets of five, and Fruit Duel scores against anyone who cuts something that was not fruit. A wrong answer scores for the other seat in all three, so accuracy is worth more than speed, and no round is longer than ninety seconds.':
      '‮Both‬ ‮players‬ ‮see‬ ‮the‬ ‮same‬ ‮thing‬ ‮at‬ ‮the‬ ‮same‬ ‮instant,‬ ‮and‬ ‮the‬ ‮only‬ ‮question‬ ‮is‬ ‮who‬ ‮answers‬ ‮first.‬ ‮Math‬ ‮Duel‬ ‮shows‬ ‮one‬ ‮sum‬ ‮and‬ ‮four‬ ‮answers,‬ ‮Match‬ ‮Rush‬ ‮hides‬ ‮a‬ ‮single‬ ‮shared‬ ‮symbol‬ ‮in‬ ‮two‬ ‮sets‬ ‮of‬ ‮five,‬ ‮and‬ ‮Fruit‬ ‮Duel‬ ‮scores‬ ‮against‬ ‮anyone‬ ‮who‬ ‮cuts‬ ‮something‬ ‮that‬ ‮was‬ ‮not‬ ‮fruit.‬ ‮A‬ ‮wrong‬ ‮answer‬ ‮scores‬ ‮for‬ ‮the‬ ‮other‬ ‮seat‬ ‮in‬ ‮all‬ ‮three,‬ ‮so‬ ‮accuracy‬ ‮is‬ ‮worth‬ ‮more‬ ‮than‬ ‮speed,‬ ‮and‬ ‮no‬ ‮round‬ ‮is‬ ‮longer‬ ‮than‬ ‮ninety‬ ‮seconds.‬',
    'Browse all {count} games': '‮Browse‬ ‮all‬ {count} ‮games‬',
    'Browse by category': '‮Browse‬ ‮by‬ ‮category‬',
    Categories: '‮Categories‬',
    Category: '‮Category‬',
    Clear: '‮Clear‬',
    'Clear all': '‮Clear‬ ‮all‬',
    'Clear recently played': '‮Clear‬ ‮recently‬ ‮played‬',
    'Clear search': '‮Clear‬ ‮search‬',
    DMCA: '‮DMCA‬',
    Deduction: '‮Deduction‬',
    'Deduction games': '‮Deduction‬ ‮games‬',
    Dice: '‮Dice‬',
    'Dice games': '‮Dice‬ ‮games‬',
    'DuelBox is a collection of small games for two people sharing one screen, and nothing else. There is no feed, no levels to work through and no lobby full of strangers: two of you, one device, and a game that finishes soon enough to play another.':
      '‮DuelBox‬ ‮is‬ ‮a‬ ‮collection‬ ‮of‬ ‮small‬ ‮games‬ ‮for‬ ‮two‬ ‮people‬ ‮sharing‬ ‮one‬ ‮screen,‬ ‮and‬ ‮nothing‬ ‮else.‬ ‮There‬ ‮is‬ ‮no‬ ‮feed,‬ ‮no‬ ‮levels‬ ‮to‬ ‮work‬ ‮through‬ ‮and‬ ‮no‬ ‮lobby‬ ‮full‬ ‮of‬ ‮strangers:‬ ‮two‬ ‮of‬ ‮you,‬ ‮one‬ ‮device,‬ ‮and‬ ‮a‬ ‮game‬ ‮that‬ ‮finishes‬ ‮soon‬ ‮enough‬ ‮to‬ ‮play‬ ‮another.‬',
    'DuelBox keeps a page on your device once you have opened it there, and this address is not one of them yet. Nothing is broken and nothing of yours is lost — the page has not arrived here.':
      '‮DuelBox‬ ‮keeps‬ ‮a‬ ‮page‬ ‮on‬ ‮your‬ ‮device‬ ‮once‬ ‮you‬ ‮have‬ ‮opened‬ ‮it‬ ‮there,‬ ‮and‬ ‮this‬ ‮address‬ ‮is‬ ‮not‬ ‮one‬ ‮of‬ ‮them‬ ‮yet.‬ ‮Nothing‬ ‮is‬ ‮broken‬ ‮and‬ ‮nothing‬ ‮of‬ ‮yours‬ ‮is‬ ‮lost‬ ‮—‬ ‮the‬ ‮page‬ ‮has‬ ‮not‬ ‮arrived‬ ‮here.‬',
    'DuelBox — 108 games for two players. Runs in your browser; nothing to install.':
      '‮DuelBox‬ ‮—‬ ‮108‬ ‮games‬ ‮for‬ ‮two‬ ‮players.‬ ‮Runs‬ ‮in‬ ‮your‬ ‮browser;‬ ‮nothing‬ ‮to‬ ‮install.‬',
    'Every category has a page of its own that says what its games have in common, names the ones worth starting with, and tells you how long a round of one takes. If you know the sort of game you want before you know which game, that is where to begin.':
      '‮Every‬ ‮category‬ ‮has‬ ‮a‬ ‮page‬ ‮of‬ ‮its‬ ‮own‬ ‮that‬ ‮says‬ ‮what‬ ‮its‬ ‮games‬ ‮have‬ ‮in‬ ‮common,‬ ‮names‬ ‮the‬ ‮ones‬ ‮worth‬ ‮starting‬ ‮with,‬ ‮and‬ ‮tells‬ ‮you‬ ‮how‬ ‮long‬ ‮a‬ ‮round‬ ‮of‬ ‮one‬ ‮takes.‬ ‮If‬ ‮you‬ ‮know‬ ‮the‬ ‮sort‬ ‮of‬ ‮game‬ ‮you‬ ‮want‬ ‮before‬ ‮you‬ ‮know‬ ‮which‬ ‮game,‬ ‮that‬ ‮is‬ ‮where‬ ‮to‬ ‮begin.‬',
    'Every game has a bot, at three strengths. It sees no more than you can see and moves no faster than a person could; what changes from one strength to the next is how far ahead it looks and how often it slips.':
      '‮Every‬ ‮game‬ ‮has‬ ‮a‬ ‮bot,‬ ‮at‬ ‮three‬ ‮strengths.‬ ‮It‬ ‮sees‬ ‮no‬ ‮more‬ ‮than‬ ‮you‬ ‮can‬ ‮see‬ ‮and‬ ‮moves‬ ‮no‬ ‮faster‬ ‮than‬ ‮a‬ ‮person‬ ‮could;‬ ‮what‬ ‮changes‬ ‮from‬ ‮one‬ ‮strength‬ ‮to‬ ‮the‬ ‮next‬ ‮is‬ ‮how‬ ‮far‬ ‮ahead‬ ‮it‬ ‮looks‬ ‮and‬ ‮how‬ ‮often‬ ‮it‬ ‮slips.‬',
    'Every game in the catalogue offers the first two of these, and any game can start the third.':
      '‮Every‬ ‮game‬ ‮in‬ ‮the‬ ‮catalogue‬ ‮offers‬ ‮the‬ ‮first‬ ‮two‬ ‮of‬ ‮these,‬ ‮and‬ ‮any‬ ‮game‬ ‮can‬ ‮start‬ ‮the‬ ‮third.‬',
    'Every game is built to the same shape, which is what makes the second one easy. The countdown, the score, the pause, the result and the rematch all come from the site rather than from the game, so they sit in the same place and behave the same way whichever one you opened. Esc pauses, for either player, in all of them.':
      '‮Every‬ ‮game‬ ‮is‬ ‮built‬ ‮to‬ ‮the‬ ‮same‬ ‮shape,‬ ‮which‬ ‮is‬ ‮what‬ ‮makes‬ ‮the‬ ‮second‬ ‮one‬ ‮easy.‬ ‮The‬ ‮countdown,‬ ‮the‬ ‮score,‬ ‮the‬ ‮pause,‬ ‮the‬ ‮result‬ ‮and‬ ‮the‬ ‮rematch‬ ‮all‬ ‮come‬ ‮from‬ ‮the‬ ‮site‬ ‮rather‬ ‮than‬ ‮from‬ ‮the‬ ‮game,‬ ‮so‬ ‮they‬ ‮sit‬ ‮in‬ ‮the‬ ‮same‬ ‮place‬ ‮and‬ ‮behave‬ ‮the‬ ‮same‬ ‮way‬ ‮whichever‬ ‮one‬ ‮you‬ ‮opened.‬ ‮Esc‬ ‮pauses,‬ ‮for‬ ‮either‬ ‮player,‬ ‮in‬ ‮all‬ ‮of‬ ‮them.‬',
    Favourites: '‮Favourites‬',
    Games: '‮Games‬',
    'Games about a lane and the traffic in it. Both players run their own strip of road side by side and the same hazards arrive for both, so nobody is unlucky in a way the other was not: Road Dodge leaves exactly one lane open, Slot Cars charges two seconds for a corner taken too fast, and Wheelie makes speed itself the thing that tips you over. Nothing here runs beyond a minute and a quarter, and Crash It is settled in twenty seconds.':
      '‮Games‬ ‮about‬ ‮a‬ ‮lane‬ ‮and‬ ‮the‬ ‮traffic‬ ‮in‬ ‮it.‬ ‮Both‬ ‮players‬ ‮run‬ ‮their‬ ‮own‬ ‮strip‬ ‮of‬ ‮road‬ ‮side‬ ‮by‬ ‮side‬ ‮and‬ ‮the‬ ‮same‬ ‮hazards‬ ‮arrive‬ ‮for‬ ‮both,‬ ‮so‬ ‮nobody‬ ‮is‬ ‮unlucky‬ ‮in‬ ‮a‬ ‮way‬ ‮the‬ ‮other‬ ‮was‬ ‮not:‬ ‮Road‬ ‮Dodge‬ ‮leaves‬ ‮exactly‬ ‮one‬ ‮lane‬ ‮open,‬ ‮Slot‬ ‮Cars‬ ‮charges‬ ‮two‬ ‮seconds‬ ‮for‬ ‮a‬ ‮corner‬ ‮taken‬ ‮too‬ ‮fast,‬ ‮and‬ ‮Wheelie‬ ‮makes‬ ‮speed‬ ‮itself‬ ‮the‬ ‮thing‬ ‮that‬ ‮tips‬ ‮you‬ ‮over.‬ ‮Nothing‬ ‮here‬ ‮runs‬ ‮beyond‬ ‮a‬ ‮minute‬ ‮and‬ ‮a‬ ‮quarter,‬ ‮and‬ ‮Crash‬ ‮It‬ ‮is‬ ‮settled‬ ‮in‬ ‮twenty‬ ‮seconds.‬',
    'Games about aiming rather than about being quick. Each one asks for a line and then a strength — the draw on the bow in Archery, the angle and the powder in Cannon Duel — and the shot then goes where it was sent while a crosswind or a moving target argues with it. Both seats fire under the same conditions, and most rounds take ninety seconds, with Tanks the quick one.':
      '‮Games‬ ‮about‬ ‮aiming‬ ‮rather‬ ‮than‬ ‮about‬ ‮being‬ ‮quick.‬ ‮Each‬ ‮one‬ ‮asks‬ ‮for‬ ‮a‬ ‮line‬ ‮and‬ ‮then‬ ‮a‬ ‮strength‬ ‮—‬ ‮the‬ ‮draw‬ ‮on‬ ‮the‬ ‮bow‬ ‮in‬ ‮Archery,‬ ‮the‬ ‮angle‬ ‮and‬ ‮the‬ ‮powder‬ ‮in‬ ‮Cannon‬ ‮Duel‬ ‮—‬ ‮and‬ ‮the‬ ‮shot‬ ‮then‬ ‮goes‬ ‮where‬ ‮it‬ ‮was‬ ‮sent‬ ‮while‬ ‮a‬ ‮crosswind‬ ‮or‬ ‮a‬ ‮moving‬ ‮target‬ ‮argues‬ ‮with‬ ‮it.‬ ‮Both‬ ‮seats‬ ‮fire‬ ‮under‬ ‮the‬ ‮same‬ ‮conditions,‬ ‮and‬ ‮most‬ ‮rounds‬ ‮take‬ ‮ninety‬ ‮seconds,‬ ‮with‬ ‮Tanks‬ ‮the‬ ‮quick‬ ‮one.‬',
    'Games about holding something in your head a few seconds longer than the person opposite. Memory Match is the sixteen-card table, where a matched pair keeps the turn, so somebody who remembers can clear it in a single visit; Pizza Memory deals an order, hides it, and asks for it back from the rail in front of you. Either one is done in about a minute.':
      '‮Games‬ ‮about‬ ‮holding‬ ‮something‬ ‮in‬ ‮your‬ ‮head‬ ‮a‬ ‮few‬ ‮seconds‬ ‮longer‬ ‮than‬ ‮the‬ ‮person‬ ‮opposite.‬ ‮Memory‬ ‮Match‬ ‮is‬ ‮the‬ ‮sixteen-card‬ ‮table,‬ ‮where‬ ‮a‬ ‮matched‬ ‮pair‬ ‮keeps‬ ‮the‬ ‮turn,‬ ‮so‬ ‮somebody‬ ‮who‬ ‮remembers‬ ‮can‬ ‮clear‬ ‮it‬ ‮in‬ ‮a‬ ‮single‬ ‮visit;‬ ‮Pizza‬ ‮Memory‬ ‮deals‬ ‮an‬ ‮order,‬ ‮hides‬ ‮it,‬ ‮and‬ ‮asks‬ ‮for‬ ‮it‬ ‮back‬ ‮from‬ ‮the‬ ‮rail‬ ‮in‬ ‮front‬ ‮of‬ ‮you.‬ ‮Either‬ ‮one‬ ‮is‬ ‮done‬ ‮in‬ ‮about‬ ‮a‬ ‮minute.‬',
    'Games about timing a jump. Each player gets a strip of their own — a sky in Happy Birds, a lane in Gravity Run, a perch in Chicken Jump — and the gap or the block arrives for both at the same moment, so the loser is whoever ran out of timing first. About a minute each, and Stampede is shorter.':
      '‮Games‬ ‮about‬ ‮timing‬ ‮a‬ ‮jump.‬ ‮Each‬ ‮player‬ ‮gets‬ ‮a‬ ‮strip‬ ‮of‬ ‮their‬ ‮own‬ ‮—‬ ‮a‬ ‮sky‬ ‮in‬ ‮Happy‬ ‮Birds,‬ ‮a‬ ‮lane‬ ‮in‬ ‮Gravity‬ ‮Run,‬ ‮a‬ ‮perch‬ ‮in‬ ‮Chicken‬ ‮Jump‬ ‮—‬ ‮and‬ ‮the‬ ‮gap‬ ‮or‬ ‮the‬ ‮block‬ ‮arrives‬ ‮for‬ ‮both‬ ‮at‬ ‮the‬ ‮same‬ ‮moment,‬ ‮so‬ ‮the‬ ‮loser‬ ‮is‬ ‮whoever‬ ‮ran‬ ‮out‬ ‮of‬ ‮timing‬ ‮first.‬ ‮About‬ ‮a‬ ‮minute‬ ‮each,‬ ‮and‬ ‮Stampede‬ ‮is‬ ‮shorter.‬',
    'Games that take their rules from a real sport and shrink the pitch to one screen. Air Hockey and Tennis run in real time with both halves moving at once; Bowling and Darts take turns instead, and the board turns to face whoever is to play. Most finish inside two minutes, and Pool is the long one at about five.':
      '‮Games‬ ‮that‬ ‮take‬ ‮their‬ ‮rules‬ ‮from‬ ‮a‬ ‮real‬ ‮sport‬ ‮and‬ ‮shrink‬ ‮the‬ ‮pitch‬ ‮to‬ ‮one‬ ‮screen.‬ ‮Air‬ ‮Hockey‬ ‮and‬ ‮Tennis‬ ‮run‬ ‮in‬ ‮real‬ ‮time‬ ‮with‬ ‮both‬ ‮halves‬ ‮moving‬ ‮at‬ ‮once;‬ ‮Bowling‬ ‮and‬ ‮Darts‬ ‮take‬ ‮turns‬ ‮instead,‬ ‮and‬ ‮the‬ ‮board‬ ‮turns‬ ‮to‬ ‮face‬ ‮whoever‬ ‮is‬ ‮to‬ ‮play.‬ ‮Most‬ ‮finish‬ ‮inside‬ ‮two‬ ‮minutes,‬ ‮and‬ ‮Pool‬ ‮is‬ ‮the‬ ‮long‬ ‮one‬ ‮at‬ ‮about‬ ‮five.‬',
    'Games where the floor is the opponent. Robot Arena puts both robots on a disc that sweeps, fires and drops things on them; Spike Attacks sends a volley down a row of standing stones that crack a little further with every blow, so the cover runs out while the volleys do not. Whoever is still standing takes the round, three rounds take the match, and a round is about a minute.':
      '‮Games‬ ‮where‬ ‮the‬ ‮floor‬ ‮is‬ ‮the‬ ‮opponent.‬ ‮Robot‬ ‮Arena‬ ‮puts‬ ‮both‬ ‮robots‬ ‮on‬ ‮a‬ ‮disc‬ ‮that‬ ‮sweeps,‬ ‮fires‬ ‮and‬ ‮drops‬ ‮things‬ ‮on‬ ‮them;‬ ‮Spike‬ ‮Attacks‬ ‮sends‬ ‮a‬ ‮volley‬ ‮down‬ ‮a‬ ‮row‬ ‮of‬ ‮standing‬ ‮stones‬ ‮that‬ ‮crack‬ ‮a‬ ‮little‬ ‮further‬ ‮with‬ ‮every‬ ‮blow,‬ ‮so‬ ‮the‬ ‮cover‬ ‮runs‬ ‮out‬ ‮while‬ ‮the‬ ‮volleys‬ ‮do‬ ‮not.‬ ‮Whoever‬ ‮is‬ ‮still‬ ‮standing‬ ‮takes‬ ‮the‬ ‮round,‬ ‮three‬ ‮rounds‬ ‮take‬ ‮the‬ ‮match,‬ ‮and‬ ‮a‬ ‮round‬ ‮is‬ ‮about‬ ‮a‬ ‮minute.‬',
    'How to play': '‮How‬ ‮to‬ ‮play‬',
    'It has not arrived here yet, like the one you just asked for.':
      '‮It‬ ‮has‬ ‮not‬ ‮arrived‬ ‮here‬ ‮yet,‬ ‮like‬ ‮the‬ ‮one‬ ‮you‬ ‮just‬ ‮asked‬ ‮for.‬',
    'It is here. Open it and play.': '‮It‬ ‮is‬ ‮here.‬ ‮Open‬ ‮it‬ ‮and‬ ‮play.‬',
    Language: '‮Language‬',
    Memory: '‮Memory‬',
    'Memory games': '‮Memory‬ ‮games‬',
    'Memory games for two players': '‮Memory‬ ‮games‬ ‮for‬ ‮two‬ ‮players‬',
    'Mute sound': '‮Mute‬ ‮sound‬',
    Name: '‮Name‬',
    'Needs a connection': '‮Needs‬ ‮a‬ ‮connection‬',
    'No download · No account · Runs on your device':
      '‮No‬ ‮download‬ ‮·‬ ‮No‬ ‮account‬ ‮·‬ ‮Runs‬ ‮on‬ ‮your‬ ‮device‬',
    'No games match “{query}”': '‮No‬ ‮games‬ ‮match‬ ‮“‬{query}‮”‬',
    'Not on this device': '‮Not‬ ‮on‬ ‮this‬ ‮device‬',
    'Not saved to this device': '‮Not‬ ‮saved‬ ‮to‬ ‮this‬ ‮device‬',
    'Nothing needs setting up. Pick a game and it opens, or read the guide first — it is one page, and it covers the seats, the keys, and what to do when there is only one of you.':
      '‮Nothing‬ ‮needs‬ ‮setting‬ ‮up.‬ ‮Pick‬ ‮a‬ ‮game‬ ‮and‬ ‮it‬ ‮opens,‬ ‮or‬ ‮read‬ ‮the‬ ‮guide‬ ‮first‬ ‮—‬ ‮it‬ ‮is‬ ‮one‬ ‮page,‬ ‮and‬ ‮it‬ ‮covers‬ ‮the‬ ‮seats,‬ ‮the‬ ‮keys,‬ ‮and‬ ‮what‬ ‮to‬ ‮do‬ ‮when‬ ‮there‬ ‮is‬ ‮only‬ ‮one‬ ‮of‬ ‮you.‬',
    'Nothing to install, nothing to sign up for':
      '‮Nothing‬ ‮to‬ ‮install,‬ ‮nothing‬ ‮to‬ ‮sign‬ ‮up‬ ‮for‬',
    'Nothing you do here is sent anywhere, because there is nowhere to send it. The games, the bots and the physics all run in your own browser, and there is no advertising, no analytics and not one cookie.':
      '‮Nothing‬ ‮you‬ ‮do‬ ‮here‬ ‮is‬ ‮sent‬ ‮anywhere,‬ ‮because‬ ‮there‬ ‮is‬ ‮nowhere‬ ‮to‬ ‮send‬ ‮it.‬ ‮The‬ ‮games,‬ ‮the‬ ‮bots‬ ‮and‬ ‮the‬ ‮physics‬ ‮all‬ ‮run‬ ‮in‬ ‮your‬ ‮own‬ ‮browser,‬ ‮and‬ ‮there‬ ‮is‬ ‮no‬ ‮advertising,‬ ‮no‬ ‮analytics‬ ‮and‬ ‮not‬ ‮one‬ ‮cookie.‬',
    'On this device': '‮On‬ ‮this‬ ‮device‬',
    'One floor, two bodies, and no turns to hide behind. Everything is decided by where you stand and how hard you arrive: Sumo Push wants the other wrestler past the edge of the ring, Spin War wants their top out of the dish, and King of the Yard wants the crown while making whoever wears it the one being chased. Nothing here runs longer than ninety seconds.':
      '‮One‬ ‮floor,‬ ‮two‬ ‮bodies,‬ ‮and‬ ‮no‬ ‮turns‬ ‮to‬ ‮hide‬ ‮behind.‬ ‮Everything‬ ‮is‬ ‮decided‬ ‮by‬ ‮where‬ ‮you‬ ‮stand‬ ‮and‬ ‮how‬ ‮hard‬ ‮you‬ ‮arrive:‬ ‮Sumo‬ ‮Push‬ ‮wants‬ ‮the‬ ‮other‬ ‮wrestler‬ ‮past‬ ‮the‬ ‮edge‬ ‮of‬ ‮the‬ ‮ring,‬ ‮Spin‬ ‮War‬ ‮wants‬ ‮their‬ ‮top‬ ‮out‬ ‮of‬ ‮the‬ ‮dish,‬ ‮and‬ ‮King‬ ‮of‬ ‮the‬ ‮Yard‬ ‮wants‬ ‮the‬ ‮crown‬ ‮while‬ ‮making‬ ‮whoever‬ ‮wears‬ ‮it‬ ‮the‬ ‮one‬ ‮being‬ ‮chased.‬ ‮Nothing‬ ‮here‬ ‮runs‬ ‮longer‬ ‮than‬ ‮ninety‬ ‮seconds.‬',
    'One game from each of twelve categories, so what you meet first is twelve different sorts of game rather than twelve versions of one.':
      '‮One‬ ‮game‬ ‮from‬ ‮each‬ ‮of‬ ‮twelve‬ ‮categories,‬ ‮so‬ ‮what‬ ‮you‬ ‮meet‬ ‮first‬ ‮is‬ ‮twelve‬ ‮different‬ ‮sorts‬ ‮of‬ ‮game‬ ‮rather‬ ‮than‬ ‮twelve‬ ‮versions‬ ‮of‬ ‮one.‬',
    'One game, and it is about asking the right question. Guess Who deals thirty characters and gives each player a different one to find, and a turn goes either on a question that halves the field or on naming a character outright — so guessing early is a real option and usually a poor one. Best of three, about a minute a game.':
      '‮One‬ ‮game,‬ ‮and‬ ‮it‬ ‮is‬ ‮about‬ ‮asking‬ ‮the‬ ‮right‬ ‮question.‬ ‮Guess‬ ‮Who‬ ‮deals‬ ‮thirty‬ ‮characters‬ ‮and‬ ‮gives‬ ‮each‬ ‮player‬ ‮a‬ ‮different‬ ‮one‬ ‮to‬ ‮find,‬ ‮and‬ ‮a‬ ‮turn‬ ‮goes‬ ‮either‬ ‮on‬ ‮a‬ ‮question‬ ‮that‬ ‮halves‬ ‮the‬ ‮field‬ ‮or‬ ‮on‬ ‮naming‬ ‮a‬ ‮character‬ ‮outright‬ ‮—‬ ‮so‬ ‮guessing‬ ‮early‬ ‮is‬ ‮a‬ ‮real‬ ‮option‬ ‮and‬ ‮usually‬ ‮a‬ ‮poor‬ ‮one.‬ ‮Best‬ ‮of‬ ‮three,‬ ‮about‬ ‮a‬ ‮minute‬ ‮a‬ ‮game.‬',
    'One game, and its whole idea is that neither role is assigned. Guard and Thief keeps the coins you can spend in the other player’s vault, so the moment you leave your own floor you are the thief and they are the guard — and you still have to come home to bank what you carried. About a minute, and a good part of it goes on deciding whether to set off at all.':
      '‮One‬ ‮game,‬ ‮and‬ ‮its‬ ‮whole‬ ‮idea‬ ‮is‬ ‮that‬ ‮neither‬ ‮role‬ ‮is‬ ‮assigned.‬ ‮Guard‬ ‮and‬ ‮Thief‬ ‮keeps‬ ‮the‬ ‮coins‬ ‮you‬ ‮can‬ ‮spend‬ ‮in‬ ‮the‬ ‮other‬ ‮player’s‬ ‮vault,‬ ‮so‬ ‮the‬ ‮moment‬ ‮you‬ ‮leave‬ ‮your‬ ‮own‬ ‮floor‬ ‮you‬ ‮are‬ ‮the‬ ‮thief‬ ‮and‬ ‮they‬ ‮are‬ ‮the‬ ‮guard‬ ‮—‬ ‮and‬ ‮you‬ ‮still‬ ‮have‬ ‮to‬ ‮come‬ ‮home‬ ‮to‬ ‮bank‬ ‮what‬ ‮you‬ ‮carried.‬ ‮About‬ ‮a‬ ‮minute,‬ ‮and‬ ‮a‬ ‮good‬ ‮part‬ ‮of‬ ‮it‬ ‮goes‬ ‮on‬ ‮deciding‬ ‮whether‬ ‮to‬ ‮set‬ ‮off‬ ‮at‬ ‮all.‬',
    'One game, and the only one in the catalogue timed by a track rather than by a clock. Disco Battle runs the same line of notes at both players at once, each note landing on that player’s own platform, and pays three for dead centre and one for near enough. A note let go costs you, and so does answering a note that was never there, all inside the forty seconds the song lasts.':
      '‮One‬ ‮game,‬ ‮and‬ ‮the‬ ‮only‬ ‮one‬ ‮in‬ ‮the‬ ‮catalogue‬ ‮timed‬ ‮by‬ ‮a‬ ‮track‬ ‮rather‬ ‮than‬ ‮by‬ ‮a‬ ‮clock.‬ ‮Disco‬ ‮Battle‬ ‮runs‬ ‮the‬ ‮same‬ ‮line‬ ‮of‬ ‮notes‬ ‮at‬ ‮both‬ ‮players‬ ‮at‬ ‮once,‬ ‮each‬ ‮note‬ ‮landing‬ ‮on‬ ‮that‬ ‮player’s‬ ‮own‬ ‮platform,‬ ‮and‬ ‮pays‬ ‮three‬ ‮for‬ ‮dead‬ ‮centre‬ ‮and‬ ‮one‬ ‮for‬ ‮near‬ ‮enough.‬ ‮A‬ ‮note‬ ‮let‬ ‮go‬ ‮costs‬ ‮you,‬ ‮and‬ ‮so‬ ‮does‬ ‮answering‬ ‮a‬ ‮note‬ ‮that‬ ‮was‬ ‮never‬ ‮there,‬ ‮all‬ ‮inside‬ ‮the‬ ‮forty‬ ‮seconds‬ ‮the‬ ‮song‬ ‮lasts.‬',
    'One game, in a category of its own because it is a race that leaves a wall behind it. Snake Clash puts two snakes in one arena where you can steer but cannot stop and cannot reverse, so the trail you have already laid is as dangerous to you as anything the other snake does. Ten pellets wins, inside two minutes.':
      '‮One‬ ‮game,‬ ‮in‬ ‮a‬ ‮category‬ ‮of‬ ‮its‬ ‮own‬ ‮because‬ ‮it‬ ‮is‬ ‮a‬ ‮race‬ ‮that‬ ‮leaves‬ ‮a‬ ‮wall‬ ‮behind‬ ‮it.‬ ‮Snake‬ ‮Clash‬ ‮puts‬ ‮two‬ ‮snakes‬ ‮in‬ ‮one‬ ‮arena‬ ‮where‬ ‮you‬ ‮can‬ ‮steer‬ ‮but‬ ‮cannot‬ ‮stop‬ ‮and‬ ‮cannot‬ ‮reverse,‬ ‮so‬ ‮the‬ ‮trail‬ ‮you‬ ‮have‬ ‮already‬ ‮laid‬ ‮is‬ ‮as‬ ‮dangerous‬ ‮to‬ ‮you‬ ‮as‬ ‮anything‬ ‮the‬ ‮other‬ ‮snake‬ ‮does.‬ ‮Ten‬ ‮pellets‬ ‮wins,‬ ‮inside‬ ‮two‬ ‮minutes.‬',
    'One limit, stated rather than buried. Your browser keeps a copy of the site and of each game after you open it, so a game you have played before opens and plays with no connection at all — but a game you have never opened is not on the device, and needs one. The catalogue marks which games are here, in words.':
      '‮One‬ ‮limit,‬ ‮stated‬ ‮rather‬ ‮than‬ ‮buried.‬ ‮Your‬ ‮browser‬ ‮keeps‬ ‮a‬ ‮copy‬ ‮of‬ ‮the‬ ‮site‬ ‮and‬ ‮of‬ ‮each‬ ‮game‬ ‮after‬ ‮you‬ ‮open‬ ‮it,‬ ‮so‬ ‮a‬ ‮game‬ ‮you‬ ‮have‬ ‮played‬ ‮before‬ ‮opens‬ ‮and‬ ‮plays‬ ‮with‬ ‮no‬ ‮connection‬ ‮at‬ ‮all‬ ‮—‬ ‮but‬ ‮a‬ ‮game‬ ‮you‬ ‮have‬ ‮never‬ ‮opened‬ ‮is‬ ‮not‬ ‮on‬ ‮the‬ ‮device,‬ ‮and‬ ‮needs‬ ‮one.‬ ‮The‬ ‮catalogue‬ ‮marks‬ ‮which‬ ‮games‬ ‮are‬ ‮here,‬ ‮in‬ ‮words.‬',
    'One of you, and a bot': '‮One‬ ‮of‬ ‮you,‬ ‮and‬ ‮a‬ ‮bot‬',
    'Only the language you choose is downloaded, and it applies straight away. Nothing is translated yet: the two pseudo languages are the English made deliberately strange, so that anything still in plain English is a string the translation work has not reached.':
      '‮Only‬ ‮the‬ ‮language‬ ‮you‬ ‮choose‬ ‮is‬ ‮downloaded,‬ ‮and‬ ‮it‬ ‮applies‬ ‮straight‬ ‮away.‬ ‮Nothing‬ ‮is‬ ‮translated‬ ‮yet:‬ ‮the‬ ‮two‬ ‮pseudo‬ ‮languages‬ ‮are‬ ‮the‬ ‮English‬ ‮made‬ ‮deliberately‬ ‮strange,‬ ‮so‬ ‮that‬ ‮anything‬ ‮still‬ ‮in‬ ‮plain‬ ‮English‬ ‮is‬ ‮a‬ ‮string‬ ‮the‬ ‮translation‬ ‮work‬ ‮has‬ ‮not‬ ‮reached.‬',
    'Opening a game once, while you have a connection, is enough: this device keeps it for next time.':
      '‮Opening‬ ‮a‬ ‮game‬ ‮once,‬ ‮while‬ ‮you‬ ‮have‬ ‮a‬ ‮connection,‬ ‮is‬ ‮enough:‬ ‮this‬ ‮device‬ ‮keeps‬ ‮it‬ ‮for‬ ‮next‬ ‮time.‬',
    Party: '‮Party‬',
    'Party games': '‮Party‬ ‮games‬',
    'Party games for two players': '‮Party‬ ‮games‬ ‮for‬ ‮two‬ ‮players‬',
    Platform: '‮Platform‬',
    'Platform games': '‮Platform‬ ‮games‬',
    Play: '‮Play‬',
    'Play now': '‮Play‬ ‮now‬',
    Privacy: '‮Privacy‬',
    'Put the phone or the laptop down between you and take a side each. A touch belongs to the side it began on even when a finger crosses the middle, and in games played turn by turn the board turns round so that whoever is to move reads it upright.':
      '‮Put‬ ‮the‬ ‮phone‬ ‮or‬ ‮the‬ ‮laptop‬ ‮down‬ ‮between‬ ‮you‬ ‮and‬ ‮take‬ ‮a‬ ‮side‬ ‮each.‬ ‮A‬ ‮touch‬ ‮belongs‬ ‮to‬ ‮the‬ ‮side‬ ‮it‬ ‮began‬ ‮on‬ ‮even‬ ‮when‬ ‮a‬ ‮finger‬ ‮crosses‬ ‮the‬ ‮middle,‬ ‮and‬ ‮in‬ ‮games‬ ‮played‬ ‮turn‬ ‮by‬ ‮turn‬ ‮the‬ ‮board‬ ‮turns‬ ‮round‬ ‮so‬ ‮that‬ ‮whoever‬ ‮is‬ ‮to‬ ‮move‬ ‮reads‬ ‮it‬ ‮upright.‬',
    Puzzle: '‮Puzzle‬',
    'Puzzle games': '‮Puzzle‬ ‮games‬',
    'Puzzles built for one person, dealt once and then played by two. Solitaire, Sudoku and Sliding Puzzle put a single board between both seats and alternate the moves, so a card sent to a foundation or a square answered correctly is a square the other player no longer has. Most take ninety seconds; Maze Paint is the short one at forty-five.':
      '‮Puzzles‬ ‮built‬ ‮for‬ ‮one‬ ‮person,‬ ‮dealt‬ ‮once‬ ‮and‬ ‮then‬ ‮played‬ ‮by‬ ‮two.‬ ‮Solitaire,‬ ‮Sudoku‬ ‮and‬ ‮Sliding‬ ‮Puzzle‬ ‮put‬ ‮a‬ ‮single‬ ‮board‬ ‮between‬ ‮both‬ ‮seats‬ ‮and‬ ‮alternate‬ ‮the‬ ‮moves,‬ ‮so‬ ‮a‬ ‮card‬ ‮sent‬ ‮to‬ ‮a‬ ‮foundation‬ ‮or‬ ‮a‬ ‮square‬ ‮answered‬ ‮correctly‬ ‮is‬ ‮a‬ ‮square‬ ‮the‬ ‮other‬ ‮player‬ ‮no‬ ‮longer‬ ‮has.‬ ‮Most‬ ‮take‬ ‮ninety‬ ‮seconds;‬ ‮Maze‬ ‮Paint‬ ‮is‬ ‮the‬ ‮short‬ ‮one‬ ‮at‬ ‮forty-five.‬',
    Racing: '‮Racing‬',
    'Racing & Trails': '‮Racing‬ ‮&‬ ‮Trails‬',
    'Racing & Trails games': '‮Racing‬ ‮&‬ ‮Trails‬ ‮games‬',
    'Racing and trail games for two': '‮Racing‬ ‮and‬ ‮trail‬ ‮games‬ ‮for‬ ‮two‬',
    'Racing games': '‮Racing‬ ‮games‬',
    Reaction: '‮Reaction‬',
    'Reaction games': '‮Reaction‬ ‮games‬',
    'Reaction games for two players': '‮Reaction‬ ‮games‬ ‮for‬ ‮two‬ ‮players‬',
    'Recently played': '‮Recently‬ ‮played‬',
    'Remove {name} from favourites': '‮Remove‬ {name} ‮from‬ ‮favourites‬',
    'Report a bug': '‮Report‬ ‮a‬ ‮bug‬',
    Rhythm: '‮Rhythm‬',
    'Rhythm games': '‮Rhythm‬ ‮games‬',
    'Round length': '‮Round‬ ‮length‬',
    'Rounds run from about 1 minute to about 5 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮1‬ ‮minute‬ ‮to‬ ‮about‬ ‮5‬ ‮minutes.‬',
    'Rounds run from about 20 seconds to about 1 minute.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮20‬ ‮seconds‬ ‮to‬ ‮about‬ ‮1‬ ‮minute.‬',
    'Rounds run from about 20 seconds to about 7 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮20‬ ‮seconds‬ ‮to‬ ‮about‬ ‮7‬ ‮minutes.‬',
    'Rounds run from about 3 minutes to about 7 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮3‬ ‮minutes‬ ‮to‬ ‮about‬ ‮7‬ ‮minutes.‬',
    'Rounds run from about 30 seconds to about 2 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮30‬ ‮seconds‬ ‮to‬ ‮about‬ ‮2‬ ‮minutes.‬',
    'Rounds run from about 35 seconds to about 3 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮35‬ ‮seconds‬ ‮to‬ ‮about‬ ‮3‬ ‮minutes.‬',
    'Rounds run from about 38 seconds to about 1 minute.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮38‬ ‮seconds‬ ‮to‬ ‮about‬ ‮1‬ ‮minute.‬',
    'Rounds run from about 40 seconds to about 1 minute.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮40‬ ‮seconds‬ ‮to‬ ‮about‬ ‮1‬ ‮minute.‬',
    'Rounds run from about 40 seconds to about 2 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮40‬ ‮seconds‬ ‮to‬ ‮about‬ ‮2‬ ‮minutes.‬',
    'Rounds run from about 40 seconds to about 5 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮40‬ ‮seconds‬ ‮to‬ ‮about‬ ‮5‬ ‮minutes.‬',
    'Rounds run from about 40 seconds to about 55 seconds.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮40‬ ‮seconds‬ ‮to‬ ‮about‬ ‮55‬ ‮seconds.‬',
    'Rounds run from about 45 seconds to about 2 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮45‬ ‮seconds‬ ‮to‬ ‮about‬ ‮2‬ ‮minutes.‬',
    'Rounds run from about 45 seconds to about 3 minutes.':
      '‮Rounds‬ ‮run‬ ‮from‬ ‮about‬ ‮45‬ ‮seconds‬ ‮to‬ ‮about‬ ‮3‬ ‮minutes.‬',
    'Saved on this device': '‮Saved‬ ‮on‬ ‮this‬ ‮device‬',
    'Search by name or category': '‮Search‬ ‮by‬ ‮name‬ ‮or‬ ‮category‬',
    'Search games': '‮Search‬ ‮games‬',
    'See all {count} →': '‮See‬ ‮all‬ {count} ‮→‬',
    Settings: '‮Settings‬',
    'Seven games, one winner': '‮Seven‬ ‮games,‬ ‮one‬ ‮winner‬',
    'Share one phone or one laptop, two of you either side of the screen. No opponent around? {seat} will take the other seat.':
      '‮Share‬ ‮one‬ ‮phone‬ ‮or‬ ‮one‬ ‮laptop,‬ ‮two‬ ‮of‬ ‮you‬ ‮either‬ ‮side‬ ‮of‬ ‮the‬ ‮screen.‬ ‮No‬ ‮opponent‬ ‮around?‬ {seat} ‮will‬ ‮take‬ ‮the‬ ‮other‬ ‮seat.‬',
    Shooter: '‮Shooter‬',
    'Shooter games': '‮Shooter‬ ‮games‬',
    Solo: '‮Solo‬',
    'Solo games': '‮Solo‬ ‮games‬',
    'Solo games played as a duel': '‮Solo‬ ‮games‬ ‮played‬ ‮as‬ ‮a‬ ‮duel‬',
    'Sort by': '‮Sort‬ ‮by‬',
    'Sound, vibration, and what this device remembers about how you play. Every change applies straight away and is kept in this browser only — nothing here is sent anywhere.':
      '‮Sound,‬ ‮vibration,‬ ‮and‬ ‮what‬ ‮this‬ ‮device‬ ‮remembers‬ ‮about‬ ‮how‬ ‮you‬ ‮play.‬ ‮Every‬ ‮change‬ ‮applies‬ ‮straight‬ ‮away‬ ‮and‬ ‮is‬ ‮kept‬ ‮in‬ ‮this‬ ‮browser‬ ‮only‬ ‮—‬ ‮nothing‬ ‮here‬ ‮is‬ ‮sent‬ ‮anywhere.‬',
    Sports: '‮Sports‬',
    'Sports games': '‮Sports‬ ‮games‬',
    'Start a game': '‮Start‬ ‮a‬ ‮game‬',
    'Start playing': '‮Start‬ ‮playing‬',
    Stealth: '‮Stealth‬',
    'Stealth games': '‮Stealth‬ ‮games‬',
    Survival: '‮Survival‬',
    'Survival games': '‮Survival‬ ‮games‬',
    'Terms of use': '‮Terms‬ ‮of‬ ‮use‬',
    'That page is not here': '‮That‬ ‮page‬ ‮is‬ ‮not‬ ‮here‬',
    'The address may have a typo in it, or the page may have moved since something linked to it. Nothing is lost — every game in the catalogue is one press away.':
      '‮The‬ ‮address‬ ‮may‬ ‮have‬ ‮a‬ ‮typo‬ ‮in‬ ‮it,‬ ‮or‬ ‮the‬ ‮page‬ ‮may‬ ‮have‬ ‮moved‬ ‮since‬ ‮something‬ ‮linked‬ ‮to‬ ‮it.‬ ‮Nothing‬ ‮is‬ ‮lost‬ ‮—‬ ‮every‬ ‮game‬ ‮in‬ ‮the‬ ‮catalogue‬ ‮is‬ ‮one‬ ‮press‬ ‮away.‬',
    'The catalogue knows which is which. While you are away from a connection it marks every game in the list as one of two things:':
      '‮The‬ ‮catalogue‬ ‮knows‬ ‮which‬ ‮is‬ ‮which.‬ ‮While‬ ‮you‬ ‮are‬ ‮away‬ ‮from‬ ‮a‬ ‮connection‬ ‮it‬ ‮marks‬ ‮every‬ ‮game‬ ‮in‬ ‮the‬ ‮list‬ ‮as‬ ‮one‬ ‮of‬ ‮two‬ ‮things:‬',
    'The games to reach for when somebody has half a minute and no appetite for a rulebook. One idea each, learned by playing it: bank more of the drifting notes in Money Grabber, take the pond before the other frog does in Frogs Fight, own more of the floor in Paint Fight. Most are over inside a minute, and none of them runs past three.':
      '‮The‬ ‮games‬ ‮to‬ ‮reach‬ ‮for‬ ‮when‬ ‮somebody‬ ‮has‬ ‮half‬ ‮a‬ ‮minute‬ ‮and‬ ‮no‬ ‮appetite‬ ‮for‬ ‮a‬ ‮rulebook.‬ ‮One‬ ‮idea‬ ‮each,‬ ‮learned‬ ‮by‬ ‮playing‬ ‮it:‬ ‮bank‬ ‮more‬ ‮of‬ ‮the‬ ‮drifting‬ ‮notes‬ ‮in‬ ‮Money‬ ‮Grabber,‬ ‮take‬ ‮the‬ ‮pond‬ ‮before‬ ‮the‬ ‮other‬ ‮frog‬ ‮does‬ ‮in‬ ‮Frogs‬ ‮Fight,‬ ‮own‬ ‮more‬ ‮of‬ ‮the‬ ‮floor‬ ‮in‬ ‮Paint‬ ‮Fight.‬ ‮Most‬ ‮are‬ ‮over‬ ‮inside‬ ‮a‬ ‮minute,‬ ‮and‬ ‮none‬ ‮of‬ ‮them‬ ‮runs‬ ‮past‬ ‮three.‬',
    'The roll is all of the luck, and the decision is what to spend it on. Dice Yatzy gives you five dice, three rolls and thirteen boxes that each take exactly one hand, so the skill is in spending a bad roll cheaply; Shut the Box is the shorter one, closing numbered tiles until nothing adds up any more. Yatzy is the longest game in the catalogue at about seven minutes.':
      '‮The‬ ‮roll‬ ‮is‬ ‮all‬ ‮of‬ ‮the‬ ‮luck,‬ ‮and‬ ‮the‬ ‮decision‬ ‮is‬ ‮what‬ ‮to‬ ‮spend‬ ‮it‬ ‮on.‬ ‮Dice‬ ‮Yatzy‬ ‮gives‬ ‮you‬ ‮five‬ ‮dice,‬ ‮three‬ ‮rolls‬ ‮and‬ ‮thirteen‬ ‮boxes‬ ‮that‬ ‮each‬ ‮take‬ ‮exactly‬ ‮one‬ ‮hand,‬ ‮so‬ ‮the‬ ‮skill‬ ‮is‬ ‮in‬ ‮spending‬ ‮a‬ ‮bad‬ ‮roll‬ ‮cheaply;‬ ‮Shut‬ ‮the‬ ‮Box‬ ‮is‬ ‮the‬ ‮shorter‬ ‮one,‬ ‮closing‬ ‮numbered‬ ‮tiles‬ ‮until‬ ‮nothing‬ ‮adds‬ ‮up‬ ‮any‬ ‮more.‬ ‮Yatzy‬ ‮is‬ ‮the‬ ‮longest‬ ‮game‬ ‮in‬ ‮the‬ ‮catalogue‬ ‮at‬ ‮about‬ ‮seven‬ ‮minutes.‬',
    'There is no app to download and no store to visit. A link opens a game, and the person you hand the device to needs nothing at all: no account, no invitation, no name typed in.':
      '‮There‬ ‮is‬ ‮no‬ ‮app‬ ‮to‬ ‮download‬ ‮and‬ ‮no‬ ‮store‬ ‮to‬ ‮visit.‬ ‮A‬ ‮link‬ ‮opens‬ ‮a‬ ‮game,‬ ‮and‬ ‮the‬ ‮person‬ ‮you‬ ‮hand‬ ‮the‬ ‮device‬ ‮to‬ ‮needs‬ ‮nothing‬ ‮at‬ ‮all:‬ ‮no‬ ‮account,‬ ‮no‬ ‮invitation,‬ ‮no‬ ‮name‬ ‮typed‬ ‮in.‬',
    'Three ways to play': '‮Three‬ ‮ways‬ ‮to‬ ‮play‬',
    'Try one of these instead.': '‮Try‬ ‮one‬ ‮of‬ ‮these‬ ‮instead.‬',
    'Turn-based games with a board between the two players, so the screen turns a hundred and eighty degrees each turn and both people read it upright from their own side of the device. Chess, Checkers and Backgammon are here in full, castling and bearing off included, alongside shorter grids like Reversi and Dots and Boxes. Chess is budgeted at five minutes; Tic Tac Toe is a minute.':
      '‮Turn-based‬ ‮games‬ ‮with‬ ‮a‬ ‮board‬ ‮between‬ ‮the‬ ‮two‬ ‮players,‬ ‮so‬ ‮the‬ ‮screen‬ ‮turns‬ ‮a‬ ‮hundred‬ ‮and‬ ‮eighty‬ ‮degrees‬ ‮each‬ ‮turn‬ ‮and‬ ‮both‬ ‮people‬ ‮read‬ ‮it‬ ‮upright‬ ‮from‬ ‮their‬ ‮own‬ ‮side‬ ‮of‬ ‮the‬ ‮device.‬ ‮Chess,‬ ‮Checkers‬ ‮and‬ ‮Backgammon‬ ‮are‬ ‮here‬ ‮in‬ ‮full,‬ ‮castling‬ ‮and‬ ‮bearing‬ ‮off‬ ‮included,‬ ‮alongside‬ ‮shorter‬ ‮grids‬ ‮like‬ ‮Reversi‬ ‮and‬ ‮Dots‬ ‮and‬ ‮Boxes.‬ ‮Chess‬ ‮is‬ ‮budgeted‬ ‮at‬ ‮five‬ ‮minutes;‬ ‮Tic‬ ‮Tac‬ ‮Toe‬ ‮is‬ ‮a‬ ‮minute.‬',
    'Twelve to start with': '‮Twelve‬ ‮to‬ ‮start‬ ‮with‬',
    'Two games built around a ball that never stops and a paddle you own one end of. Brick Blast puts a wall of bricks between the two baselines and keeps two balls in play at once; Pinball Duel gives each side a pair of flippers and a goal to defend. Both are first to five, and both are over inside a minute.':
      '‮Two‬ ‮games‬ ‮built‬ ‮around‬ ‮a‬ ‮ball‬ ‮that‬ ‮never‬ ‮stops‬ ‮and‬ ‮a‬ ‮paddle‬ ‮you‬ ‮own‬ ‮one‬ ‮end‬ ‮of.‬ ‮Brick‬ ‮Blast‬ ‮puts‬ ‮a‬ ‮wall‬ ‮of‬ ‮bricks‬ ‮between‬ ‮the‬ ‮two‬ ‮baselines‬ ‮and‬ ‮keeps‬ ‮two‬ ‮balls‬ ‮in‬ ‮play‬ ‮at‬ ‮once;‬ ‮Pinball‬ ‮Duel‬ ‮gives‬ ‮each‬ ‮side‬ ‮a‬ ‮pair‬ ‮of‬ ‮flippers‬ ‮and‬ ‮a‬ ‮goal‬ ‮to‬ ‮defend.‬ ‮Both‬ ‮are‬ ‮first‬ ‮to‬ ‮five,‬ ‮and‬ ‮both‬ ‮are‬ ‮over‬ ‮inside‬ ‮a‬ ‮minute.‬',
    'Two games with almost no rules and a great deal to think about. Pop It is a game of Nim in disguise: choose any run of neighbouring bubbles in one row, and whoever is left with the last bubble loses. Traffic Jam has the opposite temperament, two cars shouldering each other towards the water around one island — three minutes of arithmetic against forty-five seconds of shoving.':
      '‮Two‬ ‮games‬ ‮with‬ ‮almost‬ ‮no‬ ‮rules‬ ‮and‬ ‮a‬ ‮great‬ ‮deal‬ ‮to‬ ‮think‬ ‮about.‬ ‮Pop‬ ‮It‬ ‮is‬ ‮a‬ ‮game‬ ‮of‬ ‮Nim‬ ‮in‬ ‮disguise:‬ ‮choose‬ ‮any‬ ‮run‬ ‮of‬ ‮neighbouring‬ ‮bubbles‬ ‮in‬ ‮one‬ ‮row,‬ ‮and‬ ‮whoever‬ ‮is‬ ‮left‬ ‮with‬ ‮the‬ ‮last‬ ‮bubble‬ ‮loses.‬ ‮Traffic‬ ‮Jam‬ ‮has‬ ‮the‬ ‮opposite‬ ‮temperament,‬ ‮two‬ ‮cars‬ ‮shouldering‬ ‮each‬ ‮other‬ ‮towards‬ ‮the‬ ‮water‬ ‮around‬ ‮one‬ ‮island‬ ‮—‬ ‮three‬ ‮minutes‬ ‮of‬ ‮arithmetic‬ ‮against‬ ‮forty-five‬ ‮seconds‬ ‮of‬ ‮shoving.‬',
    'Two of you, one device': '‮Two‬ ‮of‬ ‮you,‬ ‮one‬ ‮device‬',
    'Two players · vs Bot': '‮Two‬ ‮players‬ ‮·‬ ‮vs‬ ‮Bot‬',
    'Two players · vs Bot · Solo': '‮Two‬ ‮players‬ ‮·‬ ‮vs‬ ‮Bot‬ ‮·‬ ‮Solo‬',
    'Two-player arcade games': '‮Two-player‬ ‮arcade‬ ‮games‬',
    'Two-player arena games': '‮Two-player‬ ‮arena‬ ‮games‬',
    'Two-player board games': '‮Two-player‬ ‮board‬ ‮games‬',
    'Two-player deduction games': '‮Two-player‬ ‮deduction‬ ‮games‬',
    'Two-player dice games': '‮Two-player‬ ‮dice‬ ‮games‬',
    'Two-player platform games': '‮Two-player‬ ‮platform‬ ‮games‬',
    'Two-player puzzle games': '‮Two-player‬ ‮puzzle‬ ‮games‬',
    'Two-player racing games': '‮Two-player‬ ‮racing‬ ‮games‬',
    'Two-player rhythm games': '‮Two-player‬ ‮rhythm‬ ‮games‬',
    'Two-player shooting and aiming games': '‮Two-player‬ ‮shooting‬ ‮and‬ ‮aiming‬ ‮games‬',
    'Two-player sports games': '‮Two-player‬ ‮sports‬ ‮games‬',
    'Two-player stealth games': '‮Two-player‬ ‮stealth‬ ‮games‬',
    'Two-player survival games': '‮Two-player‬ ‮survival‬ ‮games‬',
    'Unmute sound': '‮Unmute‬ ‮sound‬',
    'What the site remembers, it remembers on your device, and one page has all of it: the settings page lists everything kept here, writes it out to a file you can take with you, and erases the lot in one press.':
      '‮What‬ ‮the‬ ‮site‬ ‮remembers,‬ ‮it‬ ‮remembers‬ ‮on‬ ‮your‬ ‮device,‬ ‮and‬ ‮one‬ ‮page‬ ‮has‬ ‮all‬ ‮of‬ ‮it:‬ ‮the‬ ‮settings‬ ‮page‬ ‮lists‬ ‮everything‬ ‮kept‬ ‮here,‬ ‮writes‬ ‮it‬ ‮out‬ ‮to‬ ‮a‬ ‮file‬ ‮you‬ ‮can‬ ‮take‬ ‮with‬ ‮you,‬ ‮and‬ ‮erases‬ ‮the‬ ‮lot‬ ‮in‬ ‮one‬ ‮press.‬',
    'What this is': '‮What‬ ‮this‬ ‮is‬',
    'about 1 minute': '‮about‬ ‮1‬ ‮minute‬',
    'about 2 minutes': '‮about‬ ‮2‬ ‮minutes‬',
    'about 20 seconds': '‮about‬ ‮20‬ ‮seconds‬',
    'about 3 minutes': '‮about‬ ‮3‬ ‮minutes‬',
    'about 30 seconds': '‮about‬ ‮30‬ ‮seconds‬',
    'about 34 seconds': '‮about‬ ‮34‬ ‮seconds‬',
    'about 35 seconds': '‮about‬ ‮35‬ ‮seconds‬',
    'about 38 seconds': '‮about‬ ‮38‬ ‮seconds‬',
    'about 4 minutes': '‮about‬ ‮4‬ ‮minutes‬',
    'about 40 seconds': '‮about‬ ‮40‬ ‮seconds‬',
    'about 45 seconds': '‮about‬ ‮45‬ ‮seconds‬',
    'about 5 minutes': '‮about‬ ‮5‬ ‮minutes‬',
    'about 55 seconds': '‮about‬ ‮55‬ ‮seconds‬',
    'about 7 minutes': '‮about‬ ‮7‬ ‮minutes‬',
    'for two players': '‮for‬ ‮two‬ ‮players‬',
    '{count} game': '{count} ‮game‬',
    '{count} game, played by two people on one device.':
      '{count} ‮game,‬ ‮played‬ ‮by‬ ‮two‬ ‮people‬ ‮on‬ ‮one‬ ‮device.‬',
    '{count} games': '{count} ‮games‬',
    '{count} games, played by two people on one device.':
      '{count} ‮games,‬ ‮played‬ ‮by‬ ‮two‬ ‮people‬ ‮on‬ ‮one‬ ‮device.‬',
    '{games} games across {categories} categories. Every one plays with two people on one device, and every one also takes a bot in the second seat.':
      '{games} ‮games‬ ‮across‬ {categories} ‮categories.‬ ‮Every‬ ‮one‬ ‮plays‬ ‮with‬ ‮two‬ ‮people‬ ‮on‬ ‮one‬ ‮device,‬ ‮and‬ ‮every‬ ‮one‬ ‮also‬ ‮takes‬ ‮a‬ ‮bot‬ ‮in‬ ‮the‬ ‮second‬ ‮seat.‬',
  },
} as const;

export default catalogue;
