// Generated by `pnpm i18n:extract` (apps/web/src/lib/i18n/extract.test.ts) from every
// message the site can render. Do not edit by hand: change the source, or the transform in
// pseudo.ts, and regenerate. extract.test.ts fails when this file is not what it would write.

const catalogue = {
  locale: 'en-XA',
  messages: {
    ', {drawn} drawn': '⟦, {drawn} ðŕåŵñ ······⟧',
    '1 round': '⟦1 ŕöûñð ···⟧',
    'A draw': '⟦Å ðŕåŵ ···⟧',
    'A new best on this device.': '⟦Å ñéŵ ƀéšŧ öñ ŧĥïš ðéṽïçé. ··········⟧',
    'A new best.': '⟦Å ñéŵ ƀéšŧ. ····⟧',
    'A solo run has one seat, so there is nobody to hand the other to.':
      '⟦Å šöłö ŕûñ ĥåš öñé šéåŧ, šö ŧĥéŕé ïš ñöƀöðý ŧö ĥåñð ŧĥé öŧĥéŕ ŧö. ·······················⟧',
    'A solo run is one round.': '⟦Å šöłö ŕûñ ïš öñé ŕöûñð. ·········⟧',
    'All time in {game}: {p1} {wins1} — {wins2} {p2}':
      '⟦Åłł ŧïɱé ïñ {game}: {p1} {wins1} — {wins2} {p2} ·················⟧',
    'Back to all games': '⟦Ɓåçķ ŧö åłł ĝåɱéš ······⟧',
    'Best of 3': '⟦Ɓéšŧ öƒ 3 ····⟧',
    'Best of 5': '⟦Ɓéšŧ öƒ 5 ····⟧',
    'Best on this device: {best}.': '⟦Ɓéšŧ öñ ŧĥïš ðéṽïçé: {best}. ··········⟧',
    'Best {best}.': '⟦Ɓéšŧ {best}. ·····⟧',
    'Bot skill: {tier} for all {games} games':
      '⟦Ɓöŧ šķïłł: {tier} ƒöŕ åłł {games} ĝåɱéš ··············⟧',
    'Change something for the next round': '⟦Çĥåñĝé šöɱéŧĥïñĝ ƒöŕ ŧĥé ñéẋŧ ŕöûñð ·············⟧',
    Controls: '⟦Çöñŧŕöłš ···⟧',
    Critical: '⟦Çŕïŧïçåł ···⟧',
    Dismiss: '⟦Ðïšɱïšš ···⟧',
    Easy: '⟦Éåšý ··⟧',
    'Every longer length is already decided by the score so far.':
      '⟦Éṽéŕý łöñĝéŕ łéñĝŧĥ ïš åłŕéåðý ðéçïðéð ƀý ŧĥé šçöŕé šö ƒåŕ. ·····················⟧',
    Exit: '⟦Éẋïŧ ··⟧',
    Finish: '⟦Ƒïñïšĥ ···⟧',
    'Game options': '⟦Ĝåɱé öþŧïöñš ·····⟧',
    'Game over': '⟦Ĝåɱé öṽéŕ ····⟧',
    'Game over. Score {score}. {best}': '⟦Ĝåɱé öṽéŕ. Šçöŕé {score}. {best} ············⟧',
    'Game over. {outcome}.': '⟦Ĝåɱé öṽéŕ. {outcome}. ········⟧',
    'Game {n} of {total}': '⟦Ĝåɱé {n} öƒ {total} ·······⟧',
    'Game {n}: drawn': '⟦Ĝåɱé {n}: ðŕåŵñ ······⟧',
    'Game {n}: playing now': '⟦Ĝåɱé {n}: þłåýïñĝ ñöŵ ········⟧',
    'Game {n}: to come': '⟦Ĝåɱé {n}: ŧö çöɱé ······⟧',
    'Game {n}: {name} won': '⟦Ĝåɱé {n}: {name} ŵöñ ·······⟧',
    Go: '⟦Ĝö ·⟧',
    'Go again': '⟦Ĝö åĝåïñ ···⟧',
    'Go to game {n}': '⟦Ĝö ŧö ĝåɱé {n} ·····⟧',
    'Hand the device over, then continue when you have it.':
      '⟦Ĥåñð ŧĥé ðéṽïçé öṽéŕ, ŧĥéñ çöñŧïñûé ŵĥéñ ýöû ĥåṽé ïŧ. ···················⟧',
    'Hand the far seat to a person': '⟦Ĥåñð ŧĥé ƒåŕ šéåŧ ŧö å þéŕšöñ ···········⟧',
    Hard: '⟦Ĥåŕð ··⟧',
    Healthy: '⟦Ĥéåłŧĥý ···⟧',
    'I have it — continue': '⟦Ï ĥåṽé ïŧ — çöñŧïñûé ·······⟧',
    'Keep playing': '⟦Ķééþ þłåýïñĝ ·····⟧',
    Keys: '⟦Ķéýš ··⟧',
    Language: '⟦Łåñĝûåĝé ···⟧',
    'Leave the match': '⟦Łéåṽé ŧĥé ɱåŧçĥ ······⟧',
    'Leave the match?': '⟦Łéåṽé ŧĥé ɱåŧçĥ? ······⟧',
    'Leave the tournament': '⟦Łéåṽé ŧĥé ŧöûŕñåɱéñŧ ·······⟧',
    'Let the bot take the far seat': '⟦Łéŧ ŧĥé ƀöŧ ŧåķé ŧĥé ƒåŕ šéåŧ ···········⟧',
    Low: '⟦Łöŵ ··⟧',
    'Match controls': '⟦Ṁåŧçĥ çöñŧŕöłš ·····⟧',
    'Match length': '⟦Ṁåŧçĥ łéñĝŧĥ ·····⟧',
    'Match over': '⟦Ṁåŧçĥ öṽéŕ ····⟧',
    'Match over. {outcome}. {tally}.': '⟦Ṁåŧçĥ öṽéŕ. {outcome}. {tally}. ···········⟧',
    'Mute sound': '⟦Ṁûŧé šöûñð ····⟧',
    'Next round': '⟦Ñéẋŧ ŕöûñð ····⟧',
    Normal: '⟦Ñöŕɱåł ···⟧',
    'Not added to the record: the far seat changed hands during this match.':
      '⟦Ñöŧ åððéð ŧö ŧĥé ŕéçöŕð: ŧĥé ƒåŕ šéåŧ çĥåñĝéð ĥåñðš ðûŕïñĝ ŧĥïš ɱåŧçĥ. ·························⟧',
    'Only the language you choose is downloaded, and it applies straight away. Nothing is translated yet: the two pseudo languages are the English made deliberately strange, so that anything still in plain English is a string the translation work has not reached.':
      '⟦Öñłý ŧĥé łåñĝûåĝé ýöû çĥööšé ïš ðöŵñłöåðéð, åñð ïŧ åþþłïéš šŧŕåïĝĥŧ åŵåý. Ñöŧĥïñĝ ïš ŧŕåñšłåŧéð ýéŧ: ŧĥé ŧŵö þšéûðö łåñĝûåĝéš åŕé ŧĥé Éñĝłïšĥ ɱåðé ðéłïƀéŕåŧéłý šŧŕåñĝé, šö ŧĥåŧ åñýŧĥïñĝ šŧïłł ïñ þłåïñ Éñĝłïšĥ ïš å šŧŕïñĝ ŧĥé ŧŕåñšłåŧïöñ ŵöŕķ ĥåš ñöŧ ŕéåçĥéð. ···························································································⟧',
    'Pass the device': '⟦Þåšš ŧĥé ðéṽïçé ······⟧',
    'Pass to {name}': '⟦Þåšš ŧö {name} ·····⟧',
    'Pause the match': '⟦Þåûšé ŧĥé ɱåŧçĥ ······⟧',
    Paused: '⟦Þåûšéð ···⟧',
    'Play game {n}': '⟦Þłåý ĝåɱé {n} ·····⟧',
    'Play {game}': '⟦Þłåý {game} ····⟧',
    'Playing on two devices at once is not built. To carry a tournament to another device, export your data from Settings on this one and import it there.':
      '⟦Þłåýïñĝ öñ ŧŵö ðéṽïçéš åŧ öñçé ïš ñöŧ ƀûïłŧ. Ŧö çåŕŕý å ŧöûŕñåɱéñŧ ŧö åñöŧĥéŕ ðéṽïçé, éẋþöŕŧ ýöûŕ ðåŧå ƒŕöɱ Šéŧŧïñĝš öñ ŧĥïš öñé åñð ïɱþöŕŧ ïŧ ŧĥéŕé. ·····················································⟧',
    'Quit and forfeit': '⟦Ǫûïŧ åñð ƒöŕƒéïŧ ······⟧',
    'Quit match': '⟦Ǫûïŧ ɱåŧçĥ ····⟧',
    'Quitting now forfeits the match to the other player. This cannot be undone.':
      '⟦Ǫûïŧŧïñĝ ñöŵ ƒöŕƒéïŧš ŧĥé ɱåŧçĥ ŧö ŧĥé öŧĥéŕ þłåýéŕ. Ŧĥïš çåññöŧ ƀé ûñðöñé. ···························⟧',
    Rematch: '⟦Ŕéɱåŧçĥ ···⟧',
    Restart: '⟦Ŕéšŧåŕŧ ···⟧',
    Resume: '⟦Ŕéšûɱé ···⟧',
    'Round {round}': '⟦Ŕöûñð {round} ·····⟧',
    'Round {round} of {rounds}': '⟦Ŕöûñð {round} öƒ {rounds} ·········⟧',
    'Round {round}. {outcome}. {tally}.': '⟦Ŕöûñð {round}. {outcome}. {tally}. ············⟧',
    'Rounds won: {p1} {wins1}, {p2} {wins2}':
      '⟦Ŕöûñðš ŵöñ: {p1} {wins1}, {p2} {wins2} ··············⟧',
    'Saved as {file}.': '⟦Šåṽéð åš {file}. ······⟧',
    Score: '⟦Šçöŕé ··⟧',
    'Score {score}': '⟦Šçöŕé {score} ·····⟧',
    Settings: '⟦Šéŧŧïñĝš ···⟧',
    'Share result': '⟦Šĥåŕé ŕéšûłŧ ·····⟧',
    'Shared.': '⟦Šĥåŕéð. ···⟧',
    'Sound, vibration, and what this device remembers about how you play. Every change applies straight away and is kept in this browser only — nothing here is sent anywhere.':
      '⟦Šöûñð, ṽïƀŕåŧïöñ, åñð ŵĥåŧ ŧĥïš ðéṽïçé ŕéɱéɱƀéŕš åƀöûŧ ĥöŵ ýöû þłåý. Éṽéŕý çĥåñĝé åþþłïéš šŧŕåïĝĥŧ åŵåý åñð ïš ķéþŧ ïñ ŧĥïš ƀŕöŵšéŕ öñłý — ñöŧĥïñĝ ĥéŕé ïš šéñŧ åñýŵĥéŕé. ····························································⟧',
    'Swap controllers': '⟦Šŵåþ çöñŧŕöłłéŕš ······⟧',
    'The board is exactly where you left it.':
      '⟦Ŧĥé ƀöåŕð ïš éẋåçŧłý ŵĥéŕé ýöû łéƒŧ ïŧ. ··············⟧',
    'The far seat, the bot and the match length change between rounds — finish this round first.':
      '⟦Ŧĥé ƒåŕ šéåŧ, ŧĥé ƀöŧ åñð ŧĥé ɱåŧçĥ łéñĝŧĥ çĥåñĝé ƀéŧŵééñ ŕöûñðš — ƒïñïšĥ ŧĥïš ŕöûñð ƒïŕšŧ. ································⟧',
    'The picture could not be made. Try again.':
      '⟦Ŧĥé þïçŧûŕé çöûłð ñöŧ ƀé ɱåðé. Ŧŕý åĝåïñ. ···············⟧',
    'The tournament settled the seats, the bot and the length when it started. Leave the tournament to change them.':
      '⟦Ŧĥé ŧöûŕñåɱéñŧ šéŧŧłéð ŧĥé šéåŧš, ŧĥé ƀöŧ åñð ŧĥé łéñĝŧĥ ŵĥéñ ïŧ šŧåŕŧéð. Łéåṽé ŧĥé ŧöûŕñåɱéñŧ ŧö çĥåñĝé ŧĥéɱ. ·······································⟧',
    'There is no bot in this match to make harder or easier.':
      '⟦Ŧĥéŕé ïš ñö ƀöŧ ïñ ŧĥïš ɱåŧçĥ ŧö ɱåķé ĥåŕðéŕ öŕ éåšïéŕ. ····················⟧',
    Touch: '⟦Ŧöûçĥ ··⟧',
    Tournament: '⟦Ŧöûŕñåɱéñŧ ····⟧',
    'Tournament drawn': '⟦Ŧöûŕñåɱéñŧ ðŕåŵñ ······⟧',
    'Turn the device sideways for a bigger board.':
      '⟦Ŧûŕñ ŧĥé ðéṽïçé šïðéŵåýš ƒöŕ å ƀïĝĝéŕ ƀöåŕð. ················⟧',
    'Turn the device upright for a bigger board.':
      '⟦Ŧûŕñ ŧĥé ðéṽïçé ûþŕïĝĥŧ ƒöŕ å ƀïĝĝéŕ ƀöåŕð. ················⟧',
    'Unmute sound': '⟦Ûñɱûŧé šöûñð ·····⟧',
    easy: '⟦éåšý ··⟧',
    hard: '⟦ĥåŕð ··⟧',
    'in use': '⟦ïñ ûšé ···⟧',
    normal: '⟦ñöŕɱåł ···⟧',
    solo: '⟦šöłö ··⟧',
    thinking: '⟦ŧĥïñķïñĝ ···⟧',
    turn: '⟦ŧûŕñ ··⟧',
    vs: '⟦ṽš ·⟧',
    '{count} point': '⟦{count} þöïñŧ ·····⟧',
    '{count} points': '⟦{count} þöïñŧš ·····⟧',
    '{name} has {points}': '⟦{name} ĥåš {points} ·······⟧',
    '{name} has {points}, and it is their turn':
      '⟦{name} ĥåš {points}, åñð ïŧ ïš ŧĥéïŕ ŧûŕñ ···············⟧',
    '{name} has {points}, and they are thinking':
      '⟦{name} ĥåš {points}, åñð ŧĥéý åŕé ŧĥïñķïñĝ ···············⟧',
    '{name} health: {level}, {percent} percent':
      '⟦{name} ĥéåłŧĥ: {level}, {percent} þéŕçéñŧ ···············⟧',
    '{name} plays this half': '⟦{name} þłåýš ŧĥïš ĥåłƒ ········⟧',
    '{name} wins': '⟦{name} ŵïñš ····⟧',
    '{name} wins the tournament': '⟦{name} ŵïñš ŧĥé ŧöûŕñåɱéñŧ ··········⟧',
    '{name}’s skill': '⟦{name}’š šķïłł ·····⟧',
    '{p1} {wins1} — {wins2} {p2}': '⟦{p1} {wins1} — {wins2} {p2} ··········⟧',
    '{p1} {wins1} — {wins2} {p2} · first to {target} takes it':
      '⟦{p1} {wins1} — {wins2} {p2} · ƒïŕšŧ ŧö {target} ŧåķéš ïŧ ····················⟧',
    '{p1} {wins1}, {p2} {wins2}': '⟦{p1} {wins1}, {p2} {wins2} ··········⟧',
  },
} as const;

export default catalogue;
