#!/usr/bin/env python3
"""
Generate the site's typed catalogue from data/catalog.yaml.

The YAML is the single source of truth for the 107 games. The site reads a generated
TypeScript module rather than parsing YAML at runtime, so the catalogue costs nothing
at request time and a malformed entry fails the build instead of the page.

    python scripts/generate_catalog.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "apps" / "web" / "src" / "data" / "catalogue.generated.ts"
# Emitted alongside so tooling that cannot parse YAML (the scaffold CLI) reads one
# generated file rather than re-implementing a parser.
OUT_JSON = ROOT / "data" / "catalog.generated.json"

# Each archetype gets a tint and a mark so 107 tiles read as one set without 107
# hand-drawn assets. The mark names map to shapes drawn by the GameTile component.
ARCHETYPE_ART = {
    "turn-board": ("sunTint", "grid"),
    "turn-aim": ("grassTint", "target"),
    "rt-split": ("p2Tint", "split"),
    "rt-arena": ("p1Tint", "ring"),
    "rt-race": ("brandTint", "chevron"),
}

ROUND_SECONDS = {
    "turn-board": 90,
    "turn-aim": 90,
    "rt-split": 60,
    "rt-arena": 40,
    "rt-race": 75,
}


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def round_seconds_for(gid, archetype):
    """The game's own declared round length, falling back to the archetype default.

    The catalogue card and the play page were reading two different numbers for 51 of the
    107 games — the card an archetype default from ROUND_SECONDS, the game its manifest.
    A player saw "about 5 min" on the card and a 20-second match. The manifest is the
    game's own declaration and is what the shell actually uses, so it wins wherever a
    package exists; the table is only a placeholder for a row that has not been built yet.
    """
    manifest = ROOT / "packages" / "games" / gid / "src" / "manifest.ts"
    if manifest.exists():
        found = re.search(r"roundSeconds:\s*(\d+)", manifest.read_text())
        if found:
            return int(found.group(1))
    return ROUND_SECONDS.get(archetype, 60)


def main() -> None:
    catalogue = yaml.safe_load((ROOT / "data" / "catalog.yaml").read_text())
    games = catalogue["games"]

    entries = []
    seen: set[str] = set()
    for game in games:
        gid = game["id"]
        if gid in seen:
            raise SystemExit(f"duplicate game id: {gid}")
        seen.add(gid)

        archetype = game.get("archetype", "rt-split")
        tint, mark = ARCHETYPE_ART.get(archetype, ("surface", "ring"))
        modes = [m for m in (game.get("modes") or "friend").split(",") if m]

        entries.append(
            {
                "id": gid,
                "slug": slugify(game["name"]),
                "name": game["name"],
                "category": game.get("category", "Party"),
                "archetype": archetype,
                "modes": modes,
                "roundSeconds": round_seconds_for(gid, archetype),
                "tint": tint,
                "mark": mark,
                "rule": game.get("rule", ""),
                "researched": bool(game.get("rule")),
            }
        )

    entries.sort(key=lambda e: e["name"])
    categories = sorted({e["category"] for e in entries})

    body = json.dumps(entries, indent=2, ensure_ascii=False)
    cats = json.dumps(categories, ensure_ascii=False)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/generate_catalog.py from data/catalog.yaml.\n"
        "// Do not edit by hand — change the YAML and regenerate.\n\n"
        "export interface CatalogueEntry {\n"
        "  readonly id: string;\n"
        "  readonly slug: string;\n"
        "  readonly name: string;\n"
        "  readonly category: string;\n"
        "  readonly archetype: string;\n"
        "  readonly modes: readonly string[];\n"
        "  readonly roundSeconds: number;\n"
        "  readonly tint: string;\n"
        "  readonly mark: string;\n"
        "  readonly rule: string;\n"
        "  /** False when the game still has an open research issue. */\n"
        "  readonly researched: boolean;\n"
        "}\n\n"
        f"export const CATALOGUE: readonly CatalogueEntry[] = {body} as const;\n\n"
        f"export const CATEGORIES: readonly string[] = {cats} as const;\n"
    )
    OUT_JSON.write_text(json.dumps({"games": entries, "categories": categories}, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} and {OUT_JSON.relative_to(ROOT)}: "
          f"{len(entries)} games, {len(categories)} categories")


if __name__ == "__main__":
    main()
