#!/usr/bin/env python3
"""
Generate the site's typed catalogue from data/catalog.yaml.

The YAML is the single source of truth for the 107 games. The site reads a generated
TypeScript module rather than parsing YAML at runtime, so the catalogue costs nothing
at request time and a malformed entry fails the build instead of the page.

    python scripts/generate_catalog.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "apps" / "web" / "src" / "data" / "catalogue.generated.ts"
OUT_NAMES = ROOT / "apps" / "web" / "src" / "data" / "game-names.generated.ts"
# Emitted alongside so tooling that cannot parse YAML (the scaffold CLI) reads one
# generated file rather than re-implementing a parser.
OUT_JSON = ROOT / "data" / "catalog.generated.json"

# Each archetype gets a tint and a mark so 107 tiles read as one set without 107
# hand-drawn assets. The mark names map to shapes drawn by the GameTile component.
ARCHETYPE_ART = {
    "turn-board": ("sunTint", "grid"),
    "turn-aim": ("grassTint", "target"),
    "rt-split": ("p2Tint", "split"),
    "rt-arena": ("p1Tint", "ring"),
    "rt-race": ("brandTint", "chevron"),
}

ROUND_SECONDS = {
    "turn-board": 90,
    "turn-aim": 90,
    "rt-split": 60,
    "rt-arena": 40,
    "rt-race": 75,
}


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def round_seconds_for(gid, archetype):
    """The game's own declared round length, falling back to the archetype default.

    The catalogue card and the play page were reading two different numbers for 51 of the
    107 games — the card an archetype default from ROUND_SECONDS, the game its manifest.
    A player saw "about 5 min" on the card and a 20-second match. The manifest is the
    game's own declaration and is what the shell actually uses, so it wins wherever a
    package exists; the table is only a placeholder for a row that has not been built yet.
    """
    manifest = ROOT / "packages" / "games" / gid / "src" / "manifest.ts"
    if manifest.exists():
        found = re.search(r"roundSeconds:\s*(\d+)", manifest.read_text())
        if found:
            return int(found.group(1))
    return ROUND_SECONDS.get(archetype, 60)


def main() -> None:
    catalogue = yaml.safe_load((ROOT / "data" / "catalog.yaml").read_text())
    games = catalogue["games"]

    entries = []
    seen: set[str] = set()
    for game in games:
        gid = game["id"]
        if gid in seen:
            raise SystemExit(f"duplicate game id: {gid}")
        seen.add(gid)

        archetype = game.get("archetype", "rt-split")
        tint, mark = ARCHETYPE_ART.get(archetype, ("surface", "ring"))
        modes = [m for m in (game.get("modes") or "friend").split(",") if m]

        # There is deliberately no `researched` field here any more (#2514).
        #
        # It used to be emitted as `bool(game.get("rule"))` under the doc comment "False when
        # the game still has an open research issue", and it was `true` for all 108 games while
        # **107 of the 108 research issues were open** — because every game has a one-line rule
        # blurb, and that is all the expression ever tested. The site therefore shipped a
        # per-game claim that observation research had been done, derived from a field that
        # cannot know it. Its only reader, the home page's `featured` list, filtered on it and
        # removed nothing, so the falsehood was invisible from the page as well as from the data.
        #
        # What a game's research state actually depends on is whether
        # `packages/games/{id}/RESEARCH.md` exists, and today none does — see
        # `docs/research-status.md` for the count and what is blocked on a person. Nothing on the
        # site needs that fact, so it is recorded there rather than re-invented here, and
        # `apps/web/src/data/research-provenance.test.ts` fails if a research-provenance field
        # comes back before the files it would describe do.
        entries.append(
            {
                "id": gid,
                "slug": slugify(game["name"]),
                "name": game["name"],
                "category": game.get("category", "Party"),
                "archetype": archetype,
                "modes": modes,
                "roundSeconds": round_seconds_for(gid, archetype),
                "tint": tint,
                "mark": mark,
                "rule": game.get("rule", ""),
            }
        )

    entries.sort(key=lambda e: e["name"])
    categories = sorted({e["category"] for e in entries})

    body = json.dumps(entries, indent=2, ensure_ascii=False)
    cats = json.dumps(categories, ensure_ascii=False)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/generate_catalog.py from data/catalog.yaml.\n"
        "// Do not edit by hand — change the YAML and regenerate.\n\n"
        "export interface CatalogueEntry {\n"
        "  readonly id: string;\n"
        "  readonly slug: string;\n"
        "  readonly name: string;\n"
        "  readonly category: string;\n"
        "  readonly archetype: string;\n"
        "  readonly modes: readonly string[];\n"
        "  readonly roundSeconds: number;\n"
        "  readonly tint: string;\n"
        "  readonly mark: string;\n"
        "  readonly rule: string;\n"
        "}\n\n"
        f"export const CATALOGUE: readonly CatalogueEntry[] = {body} as const;\n\n"
        f"export const CATEGORIES: readonly string[] = {cats} as const;\n"
    )
    # A slug -> name map in its own module, because `PlaySurface` is the one *client*
    # component that needs a game's name and importing `CATALOGUE` for it shipped all 107
    # entries — including 4.2 KB gzipped of per-game rule prose — to every visitor, to
    # look up one string. Its own file rather than another export here, so the saving does
    # not depend on a bundler proving a top-level const unused.
    names = json.dumps({e["slug"]: e["name"] for e in entries}, indent=2, ensure_ascii=False)
    ids = json.dumps({e["slug"]: e["id"] for e in entries}, indent=2, ensure_ascii=False)
    OUT_NAMES.write_text(
        "// Generated by scripts/generate_catalog.py from data/catalog.yaml.\n"
        "// Do not edit by hand — change the YAML and regenerate.\n\n"
        "/** Every game's display name, by route slug. The only catalogue data the client\n"
        " * bundle needs: the rest is read by server components and baked into the HTML. */\n"
        f"export const GAME_NAMES: Readonly<Record<string, string>> = {names};\n\n"
        "/** Package id by route slug. The registry is imported by a client component, so\n"
        " * reading it from `CATALOGUE` pulled every game's prose into the shell. */\n"
        f"export const GAME_IDS: Readonly<Record<string, string>> = {ids};\n"
    )
    OUT_JSON.write_text(json.dumps({"games": entries, "categories": categories}, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} and {OUT_JSON.relative_to(ROOT)}: "
          f"{len(entries)} games, {len(categories)} categories")


if __name__ == "__main__":
    main()
